prgrms-be-devcourse/springboot-basic

- build.gradle
- src/main/java/org/prgrms/vouchermanager/VoucherManagerApplication.java
- src/main/java/org/prgrms/vouchermanager/configuration/AppConfiguration.java
- src/main/java/org/prgrms/vouchermanager/exception/IllegalResourceAccessException.java
- src/main/java/org/prgrms/vouchermanager/shell/VoucherManagerShell.java
- src/main/java/org/prgrms/vouchermanager/voucher/domain/AbstractVoucher.java
- src/main/java/org/prgrms/vouchermanager/voucher/domain/FixedAmountVoucher.java
- src/main/java/org/prgrms/vouchermanager/voucher/domain/PercentDiscountVoucher.java
- src/main/java/org/prgrms/vouchermanager/voucher/domain/Voucher.java
- src/main/java/org/prgrms/vouchermanager/voucher/domain/VoucherFactory.java
- src/main/java/org/prgrms/vouchermanager/voucher/domain/VoucherType.java
- src/main/java/org/prgrms/vouchermanager/voucher/repository/FileVoucherRepository.java
- src/main/java/org/prgrms/vouchermanager/voucher/repository/MemoryVoucherRepository.java
- src/main/java/org/prgrms/vouchermanager/voucher/service/VoucherService.java
- src/main/java/org/prgrms/vouchermanager/voucher/service/VoucherServiceImpl.java
- src/main/resources/application.properties
- src/main/resources/application.yaml
- src/main/resources/logback-spring.xml
- src/test/java/org/prgrms/vouchermanager/VoucherManagerApplicationTests.java
- src/test/java/org/prgrms/vouchermanager/voucher/domain/FixedAmountVoucherTest.java
- src/test/java/org/prgrms/vouchermanager/voucher/domain/PercentDiscountVoucherTest.java
- src/test/java/org/prgrms/vouchermanager/voucher/repository/FileVoucherRepositoryTest.java
- src/test/java/org/prgrms/vouchermanager/voucher/repository/MemoryVoucherRepositoryTest.java
- src/test/java/org/prgrms/vouchermanager/voucher/service/VoucherServiceImplTest.java
+ 저번 e376aaa test: MemoryVoucherRepository 커밋 이후의 내용입니다!
+ Console에서 SpringShell로 변경하여 사용하지 않게된 클래스들 삭제했습니다.
+ FileVoucherRepository 구현 + 테스트 코드 작성
+ 이전 PR에서 작성하지 않았던 테스트 코드들 작성
+ FileVoucherRepository에서 의미적절한 RuntimeException을 찾지 못해서, RuntimeException을 상속받는 커스텀 Exception을 작성하였습니다.
+ SpringShell 적용
+ help 커맨드로 명령어 출력
+ IOStream을 빈으로 등록하여 사용하면 안된다. 이 부분은 좀 더 공부해서 올리겠습니다!
+ VoucherType에서 findVoucherType static메소드를 제공하면서 Optional로 리턴하도록 작성했었는데,
findVoucherType하는 방법을 static 메소드를 지우고, Enum의 valueOf를 활용하는 방법으로 수정하였습니다.
+ 그 외에도 문맥에 따른 공백 추가 및 조언주셨던 부분 수정했습니다.!
+ 테스트 코드를 작성하면서 void를 반환하는 메소드들은 테스트하기가 좀 까다롭다고 생각했습니다. 테스트하기 좋은 코드를 작성하려면 되도록 void타입을 반환하기 보다는 의미있는 값을 리턴하는게 좋은걸까요..??
+ 단위 테스트에서 구체적인 EnumType의 값이 들어가서 나중에 EnumType이 변경되면 테스트 코드도 변경 될 것 같다고 생각했습니다. 이 부분을 어떻게 해결할지 고민중입니다!  
+ PR 주기를 짧게 …
> [2C-박현지] week1- FileVoucherRepository 추가 및 테스트 코드 리뷰 부탁드립니다.

- src/main/java/kdt/vouchermanagement/ConsoleDispatcher.java
- src/main/java/kdt/vouchermanagement/Input.java
- src/main/java/kdt/vouchermanagement/Menu.java
- src/main/java/kdt/vouchermanagement/exception/InvalidMenuException.java
- src/main/java/kdt/vouchermanagement/io/ConsoleInput.java
- src/main/java/kdt/vouchermanagement/io/Input.java
- src/test/java/kdt/vouchermanagement/ConsoleDispatcherTest.java
콘솔 입력 테스트 코드를 통과하기 위한 프로덕션 코드를 구현하였습니다.
프로덕션 코드를 구현하다보면 애플리케이션 패키지 구조를 변경하는 과정이 있을텐데, 이것도 커밋에 포함되어서 복잡해지는 것 같습니다.
패키지 구조 변경하는 것도 따로 커밋을 해야할까요?
> [2기-C]류영준 - 애플리케이션 구동 및 입력 기능 구현

- src/test/java/com/waterfogsw/voucher/voucher/VoucherControllerTests.java
- 피드백주신대로 컨트롤러부터 시작하는것이 좋을것 같아 진행방향을 변경하였습니다😊
- 컨트롤러의 voucherSave메서드에 대한 테스트 시나리오를 작성하였습니다.
> [2기-C] 김산 컨트롤러 create 메소드 테스트 시나리오 작성 

- src/main/java/kdt/vouchermanagement/Application.java
- src/main/java/kdt/vouchermanagement/global/exception/InvalidMenuException.java
- src/main/java/kdt/vouchermanagement/global/io/ConsoleInput.java
- src/main/java/kdt/vouchermanagement/global/io/Input.java
- src/main/java/kdt/vouchermanagement/global/view/ConsoleDispatcher.java
- src/main/java/kdt/vouchermanagement/global/view/Menu.java
- src/test/java/kdt/vouchermanagement/ConsoleDispatcherTest.java
도메인형 패키지 구조로 변경하였습니다. (domain 패키지 부분은 아직 작성하지 않았고 임시로 생성해두었습니다.)
> [2기-C] 류영준 - 패키지 구조 변경

- src/test/java/com/dojinyou/devcourse/voucherapplication/VoucherApplicationTests.java
1. Application 단위의 유저 시나리오 구현
- 유저 시나리오에 맞는 Test 구현
- logging 관련 테스트 삭제
- logging 관련 테스트가 결국 logger에 대한 테스트가 되어버려서 불필요하다고 생각하여 삭제하였습니다.
1. 어플리케이션 종료에 대한 테스트는 어떤 식으로 작성해야 지 궁금합니다.
2. logger 같은 library를 가져다 쓰는 것은 테스트를 하지 않아도 될 것 같다고 생각했는데 괜찮은 지 궁금합니다.
> [2기-C]유도진 - 유저 시나리오 테스트 구현

- mission/src/test/java/org/prgrms/voucher/controller/VoucherControllerTest.java
콘솔을 클라이언트 컨버터를 프론트라고 생각하고 컨트롤러 부터 서버라고 구조를 생각했습니다.
- 프론트가 변경되었을때 처리되지 않을 수 있는 로직 null검사와 공백검사를 컨트롤러에 추가했습니다.
- Context 구문과 it 구문을 조금 더 명확하게 수정했습니다.
컨트롤러는 서비스에 사용자의 요청을 전달하고 리턴값을 전달하는 역할을 한다고 생각해서 바우처 데이터 타입 에 대한 유효성 검사는 프론트에서 처리하여 서버에 전달해준다고 생각했습니다.
그래서 콘솔에서 사용자가 바우처 타입과 long 타입의 바우처 밸류를 입력하면 컨버터에서 이 두 파라미터를 바우처 객체로 변환하여 컨트롤러에 넘겨줍니다. 이 구조에 대해 피드백을 받아보고 싶습니다.
> [2기-C] 유재희 VoucherApplication controller create 기능 테스트 시나리오

- src/main/java/com/dojinyou/devcourse/voucherapplication/ApplicationController.java
- src/main/java/com/dojinyou/devcourse/voucherapplication/Command.java
- src/main/java/com/dojinyou/devcourse/voucherapplication/VoucherApplication.java
- src/main/java/com/dojinyou/devcourse/voucherapplication/view/ConsoleView.java
- src/main/java/com/dojinyou/devcourse/voucherapplication/view/InputView.java
- src/main/java/com/dojinyou/devcourse/voucherapplication/view/OutputView.java
- src/main/java/com/dojinyou/devcourse/voucherapplication/voucher/IVoucherController.java
- src/main/java/com/dojinyou/devcourse/voucherapplication/voucher/IVoucherRepository.java
- src/main/java/com/dojinyou/devcourse/voucherapplication/voucher/IVoucherService.java
- src/main/java/com/dojinyou/devcourse/voucherapplication/voucher/MemoryVoucherRepository.java
- src/main/java/com/dojinyou/devcourse/voucherapplication/voucher/Voucher.java
- src/main/java/com/dojinyou/devcourse/voucherapplication/voucher/VoucherController.java
- src/main/java/com/dojinyou/devcourse/voucherapplication/voucher/VoucherService.java
- src/main/java/com/dojinyou/devcourse/voucherapplication/voucher/VoucherType.java
- src/test/java/com/dojinyou/devcourse/voucherapplication/VoucherApplicationTests.java
1. 프로젝트 구조 설계 및 관련 클래스 생성
- Class Diagram
- 
1. 처음 class diagram을 작성할 때는 InputView, OutputView, VoucherRepository 정도만 interface로 작성했고 나머지는 필요성을 못 느꼈습니다. 일단은 그래도 interface로 추상화를 시켜 놓는 게 좋다고 생각을 해서 조금 추가를 하였는데 이에 대해서 멘토님의 의견 듣고 싶습니다.
> [2기-C]유도진 - 프로젝트 구조 설계

- src/main/java/com/waterfogsw/voucher/voucher/controller/ErrorMessages.java
- src/main/java/com/waterfogsw/voucher/voucher/controller/VoucherController.java
- src/main/java/com/waterfogsw/voucher/voucher/controller/VoucherDto.java
- src/main/java/com/waterfogsw/voucher/voucher/domain/Voucher.java
- src/main/java/com/waterfogsw/voucher/voucher/dto/VoucherDto.java
- src/main/java/com/waterfogsw/voucher/voucher/repository/VoucherMemoryRepository.java
- src/main/java/com/waterfogsw/voucher/voucher/service/VoucherService.java
- src/test/java/com/waterfogsw/voucher/voucher/VoucherControllerTests.java
- src/test/java/com/waterfogsw/voucher/voucher/VoucherRepositoryTests.java
- 숫자가 아닌 값, 존재하지 않는 VoucherType에 대해서는 추후 구성할 Converter 클래스 를 통해 null로 변환 된다고 생각하고, null인 경우에 대한 테스트 케이스를 작성하였습니다.
- null여부는 cotroller에서 확인하여 에러메시지를 리턴하고, 유효한 범위인지 여부는 service레이어에서 확인하고 에러를 controller에서 catch하여 에러메시지를 리턴한다 가정하였습니다.
- VoucherDto.Request를 통해 데이터를 전달받아 컨트롤러에서 엔티티로 변환하고, VoucherDto.Response를 통해 생성한 바우처에 대한 데이터를 응답하도록 하였습니다.
- voucher엔티티의 voucherId필드명을 id로 변경하였습니다
> [2기-C] 김산 바우처 컨트롤러 테스트 코드 작성 및 구성

- src/main/java/com/waterfogsw/voucher/voucher/dto/VoucherDto.java
- src/test/java/com/waterfogsw/voucher/voucher/VoucherControllerTests.java
> [2기-C] 김산 DTO 자료형 변경

- src/main/java/com/waterfogsw/voucher/voucher/dto/VoucherDto.java
- src/test/java/com/waterfogsw/voucher/voucher/VoucherControllerTests.java
Reverts prgrms-be-devcourse/springboot-basic#265
> Revert "[2기-C] 김산 DTO 자료형 변경"

- src/main/java/com/manager/voucher/domain/FixedDiscountVoucher.java
- src/main/java/com/manager/voucher/domain/Item.java
- src/main/java/com/manager/voucher/domain/PercentDiscountVoucher.java
- src/main/java/com/manager/voucher/domain/Product.java
- src/main/java/com/manager/voucher/domain/Voucher.java
- src/test/java/com/manager/voucher/domain/FixedDiscountVoucherTest.java
- src/test/java/com/manager/voucher/domain/PercentDiscountVoucherTest.java
- src/test/java/com/manager/voucher/domain/ProductTest.java
📌 과제 설명
SpringBoot Part1 Weekly Mission
(기본) 바우처 관리 애플리케이션
바우처 관리 애플리케이션에 단위테스트를 작성해보세요.
가능한 많은 단위 테스트코드를 작성하려고 노력해보세요.
엣지 케이스(예외 케이스)를 고려해서 작성해주세요.
Hamcrest 의 메쳐들을 다양하게 작성해보고 익숙해져 보세요.
바우처 관리 애플리케이션에서도 과정에서 다루었던 고객을 적용해보세요.
customers 테이블 정의 및 추가
CustomerRepository 추가 및 JdbcTemplate을 사용해서 구현
(1주차를 파일로 관리하게 했다.) 바우처 정보를 DB로 관리해보세요.
바우처에 엔터티에 해당하는 vouchers 테이블을 한번 정의해보세요.
바우처 레포지토리를 만들어보세요. (JdbcTemplate을 사용해서 구현)
기존의 파일에서 바우처를 관리한 것을 vouchers 테이블을 통해서 CRUD가 되게 해보세요.
✅ 피드백 반영사항 
testcase중에 isExpired()부분이 false만 나오기 때문에 확인 불가 -> 생성자에 expireDate 추가하여 두가지 인자 받게 하였습니다
item 객체를 생성하여 해당 바우처 할인을 amount 와 percent방법으로 적용했습니다
✅ PR 포인트 & 궁금한 점
테스트 케이스를 더 추가 했습니다 domain 객체를 추가 했지만 이후에 요구사항이 바뀔수도 있는데 할인을 적용하는 방식과 테스트 케이스를 이렇게 추가해도 될지 확인부탁드립니다.
> [2기 - C]변주한 Voucher와 Product 테스트케이스와 도메인 세부구현 진행 하였습니다

- src/main/java/com/example/voucher/VoucherApplication.java
- src/main/java/com/example/voucher/io/ConsoleReader.java
- src/main/java/com/example/voucher/io/Input.java
- src/test/java/com/example/voucher/VoucherApplicationTests.java
명령어를 출력하는 메서드(Output.printPrompt)와 명령어를 입력받는 메서드(Input.getCommand)는 이 메서드를 사용하는 클라이언트인 VoucherApplication의 관점에서 보았을 때 관련성이 높다는 생각이 들었고 이를 하나의 메서드에서 호출하게 하는 편이 낫겠다는 생각이 들었습니다.
그래서 VoucherApplication.getCommand()에서 두 가지 메서드를 함께 호출하는 식으로 변경하고 이를 테스트하였습니다!
> [2기-C] 정하영 기존 테스트 코드 수정

- src/main/java/kdt/vouchermanagement/domain/voucher/converter/VoucherRequestConverter.java
- src/main/java/kdt/vouchermanagement/domain/voucher/domain/VoucherType.java
- src/main/java/kdt/vouchermanagement/global/view/ConsoleDispatcher.java
- src/main/java/kdt/vouchermanagement/global/view/Menu.java
📌 과제 설명
*테스트 코드를 바탕으로 바우처 DTO 변환을 구현하였습니다.
#🗺️ 클래스 다이어그램
> [2기-C]류영준 바우처 DTO 변환 구현

- mission/src/main/java/org/prgrms/voucher/dto/VoucherDto.java
- mission/src/main/java/org/prgrms/voucher/response/ResponseState.java
- mission/src/test/java/org/prgrms/voucher/controller/VoucherControllerTest.java
Response DTO 객체 필드에 응답 상태를 추가했습니다. 컨트롤러에서 예외 여부에 따라 응답상태를 체크해 Converter에 전달하면 Converter에서 예외상태를 확인해 사용자에게 재입력을 받거나 프로그램을 시작지점으로 돌릴 계획입니다.
- VoucherDto.CreateVoucherResponse 구성 추가
- Controller test코드에 ServiceMock의 반환값을 Controller에서 받기 위해 생성하는 바우처 객체를 클래스 필드로 이동했습니다.
0을 검사하고 null을 받지 않는것으로 처리하도록 Request Dto에서 voucherValue를 primitive타입으로 변경했습니다.
controll 구현을 
```java
/*Controller*/
public VoucherDto.CreateVoucherResponse create(VoucherDto.CreateVoucherRequest requestDto) {
try{
Voucher voucher = voucherService.create(requestDto);
return new VoucherDto.CreateVoucherResponse(voucher.getVoucherId());
}catch (NullPointerException e){
logger.info("bad request...");
return new VoucherDto.CreateVoucherResponse(-1L, ResponseState.BAD_REQUEST);
}
}
```
이런 방식으로 진행할 계획입니다.
> [2기-C] 유재희 Voucher Application 테스트코드 수정, DTO구조 변경

- src/main/java/com/dojinyou/devcourse/voucherapplication/view/ConsoleView.java
- src/main/java/com/dojinyou/devcourse/voucherapplication/view/InputView.java
- src/main/java/com/dojinyou/devcourse/voucherapplication/view/OutputView.java
- src/test/java/com/dojinyou/devcourse/voucherapplication/view/ConsoleViewTest.java
1. 입출력에 대한 기능 구현
1. Interface에 필요한 함수 추가
2. Console 입출력을 위한 ConsoleVIew Class 구현
> [2기-C]유도진 - 입출력 기능 구현

- src/main/java/com/example/voucher/CommandType.java
- src/main/java/com/example/voucher/VoucherApplication.java
- src/main/java/com/example/voucher/VoucherType.java
- src/main/java/com/example/voucher/controller/VoucherController.java
- src/main/java/com/example/voucher/exception/ErrorMessage.java
- src/main/java/com/example/voucher/io/ConsoleReader.java
- src/main/java/com/example/voucher/io/ConsoleWriter.java
- src/main/java/com/example/voucher/io/Input.java
- src/main/java/com/example/voucher/io/Output.java
- src/test/java/com/example/voucher/VoucherApplicationTests.java
* input에서 할인 값을 문자열로 받아서 int형으로 변환 중에 예외가 발생한다면 로그를 남기고 예외를 VoucherApplication에 넘겨 콘솔 출력하는 구조입니다.
* 바우처 타입과 명령어 입력의 경우는 지원하지 않는 값일 경우 Enum 클래스의 of 메서드에서 EMPTY를 반환합니다. 
* 바우처에 대한 처리는 VoucherApplication -> VoucherController에 위임하는 구조입니다.
> [2기-C] 정하영 create기능에 대한 VoucherApplication 테스트 구현

- src/main/java/com/example/voucher/VoucherApplication.java
- src/main/java/com/example/voucher/io/ConsoleReader.java
- src/main/java/com/example/voucher/io/ConsoleWriter.java
- src/main/java/com/example/voucher/io/Input.java
- src/main/java/com/example/voucher/io/Output.java
- src/test/java/com/example/voucher/VoucherApplicationTests.java
- src/test/java/com/example/voucher/io/InputTest.java
* Input, Output 의 경우 호출하는 코드에서 해당 메서드를 정확하게 호출하는지를 테스트 하는 것으로 하였고 ,
* 예외 처리가 필요한 메서드인 Input.getDiscountAmount() 메서드만 예외 처리를 테스트 하였습니다.
* 콘솔 입출력 기능을 하는 ConsoleReader, ConsoleWriter를 구현하였습니다.
> [2기-C] 정하영 입력에 대한 예외 처리 테스트, 콘솔 입출력 기능 구현

- src/main/java/com/waterfogsw/voucher/voucher/controller/ErrorMessages.java
- src/main/java/com/waterfogsw/voucher/voucher/controller/VoucherController.java
- src/main/java/com/waterfogsw/voucher/voucher/dto/VoucherDto.java
- src/main/java/com/waterfogsw/voucher/voucher/service/VoucherManageService.java
- src/test/java/com/waterfogsw/voucher/voucher/VoucherControllerTests.java
- VoucherDto 내부에 도메인으로의 변환 로직을 구현하였습니다.
- 도메인 변환 로직에서 값에 대한 유효성 검사를 진행하고, 에러발생시 controller에서 에러값을 담은 응답을 반환하도록 구현하였습니다.
> [2기-C] 김산 Controller 구현

- src/main/java/com/waterfogsw/voucher/voucher/controller/VoucherController.java
- src/test/java/com/waterfogsw/voucher/voucher/VoucherControllerTests.java
- src/test/java/com/waterfogsw/voucher/voucher/VoucherServiceTests.java
- VoucherService 의 voucherAdd 메서드 에 대한 테스트 시나리오를 작성하였습니다.
- 컨트롤러의 voucherSave메서드의 이름을 해당 명칭보다는 등록의 개념에 가까운 voucherAdd로 이름을 변경하였습니다.
> [2기-C] 김산 테스트 시나리오 작성 

- src/main/java/com/example/voucher/VoucherApplication.java
- src/main/java/com/example/voucher/controller/VoucherController.java
- src/main/java/com/example/voucher/domain/voucher/Voucher.java
- src/main/java/com/example/voucher/domain/voucher/VoucherType.java
- src/main/java/com/example/voucher/service/voucher/VoucherService.java
- src/main/java/com/example/voucher/service/voucher/VoucherServiceImpl.java
- src/test/java/com/example/voucher/VoucherApplicationTests.java
- src/test/java/com/example/voucher/controller/VoucherControllerTest.java
* service에 도메인 생성 로직을 넣을 예정입니다!
> [2기-C] 정하영 VoucherController save 메서드에 대한 테스트 구현

- src/main/java/com/example/voucher/domain/voucher/Voucher.java
- src/test/java/com/example/voucher/controller/VoucherControllerTest.java
- src/test/java/com/example/voucher/domain/FixedAmountVoucherTest.java
- src/test/java/com/example/voucher/domain/PercentDiscountVoucherTest.java
* FixedAmountVoucher, PercentDiscountVoucher에 대한 성공, 실패 테스트 케이스를 작성하였습니다.
> [2기-C] 정하영 Voucher 도메인에 대한 테스트 구현

- src/main/java/kdt/vouchermanagement/domain/voucher/controller/VoucherConsoleController.java
- src/main/java/kdt/vouchermanagement/domain/voucher/service/VoucherService.java
- src/main/java/kdt/vouchermanagement/global/response/Response.java
- src/test/java/kdt/vouchermanagement/ConsoleDispatcherTest.java
- src/test/java/kdt/vouchermanagement/VoucherConsoleControllerTest.java
전역적으로 사용할 수 있는 Response 클래스를 생성하여 기존에 작성하였던 테스트 코드들을 수정하였습니다.
그에 맞춰서 구조도 변경되었습니다.
> [2기-C]류영준 - Response 클래스 도입으로 인한 테스트 코드 수정 & 구조 수정

- src/main/java/com/example/voucher/VoucherApplication.java
- src/main/java/com/example/voucher/controller/VoucherController.java
- src/main/java/com/example/voucher/domain/voucher/FixedAmountVoucher.java
- src/main/java/com/example/voucher/domain/voucher/PercentDiscountVoucher.java
- src/main/java/com/example/voucher/io/ConsoleWriter.java
- src/main/java/com/example/voucher/io/Output.java
- src/test/java/com/example/voucher/VoucherApplicationTests.java
- src/test/java/com/example/voucher/controller/VoucherControllerTest.java
* Output 클래스는 콘솔 출력하는 행위를 하게 되는데 이는 예외를 앞단으로 넘기지 않고 예외가 발생한 곳에서 로거를 통해 콘솔 출력하는식으로도 구현이 가능합니다.  그런데 Output 클래스는 사용자에게 적절한 응답을 내려주는 역할을 하기 때문에 로거를 사용하여 남기는 콘솔 출력과는 구분해주어야 한다는 생각이 들었습니다.
* 그래서 역할을 명확하게 구분하기 위해 일종의 dispatcherServlet 역할을 하는 VoucherApplication으로 예외가 전달되면 VoucherApplication에서 Output 클래스를 이용해 사용자에게 적절한 메시지를 전달하는 것으로 변경하였습니다.
> [2기-C] 정하영 Output 클래스의 역할에 따른 명확한 책임을 가지도록 수정

- src/main/java/com/example/voucher/domain/voucher/VoucherType.java
- src/main/java/com/example/voucher/domain/voucher/repository/VoucherMemoryRepository.java
- src/main/java/com/example/voucher/domain/voucher/repository/VoucherRepository.java
- src/main/java/com/example/voucher/service/voucher/VoucherServiceImpl.java
- src/test/java/com/example/voucher/VoucherApplicationTests.java
- src/test/java/com/example/voucher/controller/VoucherControllerTest.java
- src/test/java/com/example/voucher/domain/FixedAmountVoucherTest.java
- src/test/java/com/example/voucher/domain/PercentDiscountVoucherTest.java
- src/test/java/com/example/voucher/io/InputTest.java
- src/test/java/com/example/voucher/service/VoucherServiceTest.java
* VoucherService 테스트 구현과 VoucherService에서 발생하는 예외가 VoucherController, VoucherApplication에 전달되는지 확인하는 테스트를 추가하였습니다!
> [2기-C] 정하영 VoucherService 테스트와 VoucherApplication, VoucherController 테스트 추가

- src/main/java/com/dojinyou/devcourse/voucherapplication/view/ConsoleView.java
- src/main/java/com/dojinyou/devcourse/voucherapplication/view/OutputView.java
- src/test/java/com/dojinyou/devcourse/voucherapplication/ApplicationControllerTest.java
- src/test/java/com/dojinyou/devcourse/voucherapplication/VoucherApplicationTest.java
- src/test/java/com/dojinyou/devcourse/voucherapplication/view/ConsoleViewTest.java
1. applicationController 테스트 작성 및 스캐너 주입 방식 수정
2. VoucherApplication Test 클래스명 수정
> [2기-C]유도진 - application controller 테스트 코드 작성

- src/main/java/kdt/vouchermanagement/domain/voucher/controller/VoucherConsoleController.java
- src/main/java/kdt/vouchermanagement/domain/voucher/domain/FixedAmountVoucher.java
- src/main/java/kdt/vouchermanagement/domain/voucher/domain/PercentDiscountVoucher.java
- src/main/java/kdt/vouchermanagement/domain/voucher/domain/Voucher.java
- src/main/java/kdt/vouchermanagement/domain/voucher/domain/VoucherType.java
- src/main/java/kdt/vouchermanagement/domain/voucher/dto/VoucherRequest.java
- src/main/java/kdt/vouchermanagement/global/response/Response.java
- src/main/java/kdt/vouchermanagement/global/view/ConsoleDispatcher.java
- src/test/java/kdt/vouchermanagement/VoucherRequestTest.java
- src/test/java/kdt/vouchermanagement/VoucherTypeTest.java
create Voucher 기능을 위하여 DTO 변환과 controller 프로덕션 코드를 구현하였습니다.
> [2기-C]류영준 create Voucher 기능 DTO 변환 & controller 프로덕션 코드 구현

- src/main/java/kdt/vouchermanagement/domain/voucher/controller/VoucherConsoleController.java
- src/main/java/kdt/vouchermanagement/domain/voucher/dto/VoucherRequest.java
VoucherType 유효성 검사를 DTO 내부 로직으로 이동시켰습니다.
> [2기-C]류영준 VoucherType 유효성 검사 리팩토링

- mission/src/main/java/org/prgrms/voucher/controller/VoucherController.java
- mission/src/main/java/org/prgrms/voucher/dto/VoucherDto.java
- mission/src/main/java/org/prgrms/voucher/models/FixedAmountVoucher.java
- mission/src/main/java/org/prgrms/voucher/models/Voucher.java
- mission/src/main/java/org/prgrms/voucher/models/VoucherType.java
- mission/src/main/java/org/prgrms/voucher/response/Response.java
- mission/src/test/java/org/prgrms/voucher/controller/VoucherControllerTest.java
create 기능을 구현하기위해 구현체를 추가하고 기존에 잘못 구성한 코드를 수정했습니다.
- dto 내 메서드 삭제
- Long voucherId 로 변경
- dto를 record 타입으로 변경했습니다. 가독성 + 불변 처리
- Response 객체 필드명 수정
- log 처리 방식 수정
- dto 라인 정리
- 테스트코드를 의도와 다르게 짜서 수정했습니다. Controller에서 예외를 던지지않고 처리하기 때문에 기존에 throw를 검사하는 코드에서 예외처리를 확인하는 코드로 변경했습니다.
- 컨트롤러의 create 기능을 구현했습니다. 테스트를 성공시키며 구현했습니다.
> [2기-C] 유재희 VoucherApp 컨트롤러 create 구현

- src/main/java/com/waterfogsw/voucher/voucher/domain/FixedAmountVoucher.java
- src/main/java/com/waterfogsw/voucher/voucher/domain/PercentDiscountVoucher.java
- src/main/java/com/waterfogsw/voucher/voucher/domain/Voucher.java
- src/main/java/com/waterfogsw/voucher/voucher/dto/VoucherDto.java
- src/test/java/com/waterfogsw/voucher/voucher/VoucherControllerTests.java
- src/test/java/com/waterfogsw/voucher/voucher/VoucherRepositoryTests.java
- 바우처 타입에 따라 추상클래스를 상속하는 형태로 변경하였습니다.
> [2기 - C] 김산 추상클래스 상속 형태로 변경

- src/main/java/kdt/vouchermanagement/domain/voucher/domain/Voucher.java
Voucher 도메인 추상 클래스의 voucherId에 final 선언을 하였습니다.
> [2기-C]류영준 voucherId final 선언

- src/test/java/com/dojinyou/devcourse/voucherapplication/CommandTest.java
> [2기-C] 유도진 - Command Type에 대한 테스트 코드 작성

- src/main/java/com/dojinyou/devcourse/voucherapplication/Command.java
> [2기-C] 유도진 - Command type 구현

- mission/src/main/java/org/prgrms/voucher/controller/VoucherController.java
- mission/src/main/java/org/prgrms/voucher/dto/VoucherDto.java
- mission/src/main/java/org/prgrms/voucher/models/VoucherType.java
- mission/src/main/java/org/prgrms/voucher/repository/VoucherMemoryRepository.java
- mission/src/main/java/org/prgrms/voucher/repository/VoucherRepository.java
- mission/src/main/java/org/prgrms/voucher/service/VoucherService.java
- mission/src/test/java/org/prgrms/voucher/controller/VoucherControllerTest.java
- mission/src/test/java/org/prgrms/voucher/service/VoucherServiceTest.java
서비스 테스트 시나리오를 머지를 안하고 다음 푸시를 진행했습니다...주의하겠습니다 죄송합니다 ㅠㅠ
서비스 레이어 테스트 시나리오코드를 작성했습니다.
우선 pr 내용과 다른 VoucherDTO 부분은 네이밍 변경을 했는데 PR로 쪼개기 너무 작다고 생각하여 이번 pr에 추가했습니다.
테스트 시나리오를 작성하고 프로덕션 코드 인터페이스를 작성했습니다.
> [2기-C] 유재희 - Test : ServiceTest 코드 작성

- mission/src/main/java/org/prgrms/voucher/dto/VoucherDto.java
- mission/src/main/java/org/prgrms/voucher/models/FixedAmountVoucher.java
- mission/src/main/java/org/prgrms/voucher/models/VoucherType.java
- mission/src/main/java/org/prgrms/voucher/service/VoucherService.java
Service 레이어의 create 메서드를 구현했습니다.
> [2기-C] 유재희 Service create메서드 구현

- mission/src/test/java/org/prgrms/voucher/repository/VoucherMemoryRepositoryTest.java
VoucherMemoryRepository save 메서드의 테스트 시나리오 입니다.
> [2기 - C] 유재희 :white_check_mark: test : Repository create 시나리오 작성

- build.gradle
- src/main/java/com/example/voucher/domain/voucher/FixedAmountVoucher.java
- src/main/java/com/example/voucher/domain/voucher/PercentDiscountVoucher.java
- src/main/java/com/example/voucher/domain/voucher/Voucher.java
- src/main/java/com/example/voucher/domain/voucher/VoucherType.java
- src/main/java/com/example/voucher/domain/voucher/repository/VoucherIdGenerator.java
- src/main/java/com/example/voucher/domain/voucher/repository/VoucherMemoryRepository.java
- src/main/java/com/example/voucher/domain/voucher/repository/VoucherRepository.java
- src/main/java/com/example/voucher/exception/ErrorMessage.java
- src/main/java/com/example/voucher/service/voucher/VoucherServiceImpl.java
- src/test/java/com/example/voucher/VoucherApplicationTests.java
- src/test/java/com/example/voucher/domain/FixedAmountVoucherTest.java
- src/test/java/com/example/voucher/domain/PercentDiscountVoucherTest.java
- src/test/java/com/example/voucher/domain/repository/VoucherMemoryRepositoryTest.java
- src/test/java/com/example/voucher/io/InputTest.java
- src/test/java/com/example/voucher/service/VoucherServiceTest.java
* VoucherId를 중복되지 않게 생성하는 역할을 하는 VoucherIdGenerator를 만들었습니다!
> [2기-C] 정하영 VoucherMemoryRepository save 메서드 테스트

- src/test/java/com/waterfogsw/voucher/voucher/VoucherServiceTests.java
- VoucherService addVoucher 메서드에 대한 테스트 코드입니다.
> [2기-C] 김산 :white_check_mark: Test: VoucherService 테스트 코드 작성

- mission/src/main/java/org/prgrms/voucher/repository/IdGenerator.java
- mission/src/main/java/org/prgrms/voucher/repository/VoucherMemoryRepository.java
- mission/src/test/java/org/prgrms/voucher/repository/VoucherMemoryRepositoryTest.java
Repository save 메서드 테스트코드 작성 및 구현을 진행했습니다.
> [2기-C] 유재희 :white_check_mark: test : Repository save 테스트 코드 작성, 구현

- src/main/java/com/waterfogsw/voucher/voucher/service/VoucherManageService.java
- Service의 saveVoucher메서드에 대한 프로덕션 코드 작성입니다.
> [2기 - C] 김산 :sparkles: Feat: saveVoucher 프로덕션 코드 작성

- mission/src/test/java/org/prgrms/voucher/controller/VoucherControllerTest.java
Controller list 기능 테스트 시나리오입니다. 
실패케이스를 생각해봤는데 받는 인자도 없고 반환을 계속 반환해서 어떤 부분에서 실패가 날지 도저히 감이 오지않았습니다.
제가 놓친 부분이 있을까요?
> :white_check_mark: test : Controller list 기능 테스트 시나리오

- src/test/java/com/waterfogsw/voucher/voucher/VoucherMemoryRepositoryTests.java
- VoucherMemoryRepository에 대한 테스트 시나리오 입니다.
> [2기 - C] 김산 :white_check_mark: VoucherMemoryRepository 테스트 시나리오 작성

- src/test/java/com/waterfogsw/voucher/voucher/VoucherMemoryRepositoryTests.java
VoucherMemoryRepository 에대한 테스트 코드 작성입니다.
> [2기-C] 김산 :white_check_mark: VoucherMemoryRepository 테스트 코드 작성

- mission/src/main/java/org/prgrms/voucher/controller/VoucherController.java
- mission/src/main/java/org/prgrms/voucher/service/VoucherService.java
- mission/src/test/java/org/prgrms/voucher/controller/VoucherControllerTest.java
Controller list 테스트코드 작성 및 구현을 완료했습니다.
초기에 시나리오, 작성, 구현은 유도리있게 PR을 쪼개라고 하셔서 변경내용이 많지 않다고 생각되어 동시에 올렸습니다.
감사합니다!
> [2기-C] 유재희 :sparkles: feat : Controller list 테스트 작성, 구현

- src/test/java/com/dojinyou/devcourse/voucherapplication/ApplicationControllerTest.java
1. ApplicationController Test 코드 수정
- 컨트롤러 구현 중 함수 변경 발생으로 인한 테스트 코드 선 수정입니다.
> [2기-C] 유도진 - application controller 테스트 코드 수정

- src/main/java/kdt/vouchermanagement/domain/voucher/controller/VoucherConsoleController.java
- src/main/java/kdt/vouchermanagement/domain/voucher/repository/VoucherRepository.java
- src/main/java/kdt/vouchermanagement/global/response/Response.java
- src/test/java/kdt/vouchermanagement/VoucherConsoleControllerTest.java
- src/test/java/kdt/vouchermanagement/VoucherServiceTest.java
create FixedAmountVoucher 기능 테스트 코드와 기능 구현하였습니다.
> [2기-C]류영준 - create FixedAmountVoucher 기능 테스트 코드와 기능 구현

- mission/src/test/java/org/prgrms/voucher/service/VoucherServiceTest.java
서비스 레이어 list기능 테스트 시나리오를 작성했습니다.
다음 PR에 프로덕션 코드 내용이 적으면 테스트 코드와 프로덕션코드 동시에 PR 올리겠습니다.
감사합니다!
> :white_check_mark: test : Service list 테스트 시나리오 작성

- mission/src/main/java/org/prgrms/voucher/repository/VoucherMemoryRepository.java
- mission/src/main/java/org/prgrms/voucher/repository/VoucherRepository.java
- mission/src/main/java/org/prgrms/voucher/service/VoucherService.java
- mission/src/test/java/org/prgrms/voucher/service/VoucherServiceTest.java
Service list 테스트 코드 작성 및 구현입니다.
제가 요구사항의 list를 생각해서 메서드 이름을 생각없이 list로 지었습니다... 
리뷰때 지적해주신 부분인데 죄송합니다 ㅠㅠ 
지금은 기능 구현하는 PR이니 추후에 리팩토링할 때 getList() 등으로 수정하도록하겠습니다!
감사합니다
> [2기-C] 유재희 :sparkles: test : Service list 테스트 코드 작성, 구현

- src/main/java/kdt/vouchermanagement/domain/voucher/controller/VoucherConsoleController.java
- src/main/java/kdt/vouchermanagement/domain/voucher/domain/FixedAmountVoucher.java
- src/main/java/kdt/vouchermanagement/domain/voucher/domain/PercentDiscountVoucher.java
- src/main/java/kdt/vouchermanagement/domain/voucher/domain/Voucher.java
- src/main/java/kdt/vouchermanagement/domain/voucher/exception/DuplicateVoucherException.java
- src/main/java/kdt/vouchermanagement/domain/voucher/repository/VoucherMemoryRepository.java
- src/main/java/kdt/vouchermanagement/domain/voucher/service/VoucherServiceImpl.java
- src/test/java/kdt/vouchermanagement/VoucherConsoleControllerTest.java
- src/test/java/kdt/vouchermanagement/VoucherServiceTest.java
create FixedAmountVoucher 기능 프로덕션 코드 구현하였습니다.
> [2기-C]류영준 - create FixedAmountVoucher 기능 프로덕션 코드 구현

- src/main/java/com/waterfogsw/voucher/voucher/repository/KeyGenerator.java
- src/main/java/com/waterfogsw/voucher/voucher/repository/VoucherMemoryRepository.java
- Voucher 저장을 위한 프로덕션 코드를 구현하였습니다.
- KeyGenerator를 따로두어 id값 생성을 위임하였습니다.
> [2기 - C] 김산 :sparkles: Feat: Voucher 저장 프로덕션 코드 구현

- src/test/java/com/waterfogsw/voucher/voucher/VoucherServiceTests.java
> [2기 - C] 김산 :recycle: Refactor: 메서드명 기존으로 변경

- src/main/java/com/dojinyou/devcourse/voucherapplication/Command.java
1. Command List 출력 문자열 리팩토링
- 각 리스트마다 줄바꿈을 추가하였습니다.
- "to" 문자열이 description에 모두 추가되어 있어 삭제하였습니다.
- 기능 구현이 우선 시 되는 상황에서 리팩토링을 진행한 이유입니다.
1. application cotroller 구현 중 command list 문자열 출력에 줄바꿈이 없어 명령어 입력 시 구분이 잘 되지 않았습니다.
2. 해당 수정이 많지 않아서 빠르게 할 수 있다고 판단하였습니다.
> [2기-C] 유도진 - command 문자열 리팩토링

- src/main/java/com/example/voucher/io/ConsoleWriter.java
- src/main/java/com/example/voucher/io/Output.java
* 바우처 조회 기능 구현 중 Output.printMessage()에서 파라미터가 String 으로 고정된 것으로 인해 기능을 구현할 수 없어 타입을 제네릭으로 변경하였습니다.
> [2기-C] 정하영 Output.printMessage 파라미터 타입 변경

- src/test/java/com/waterfogsw/voucher/voucher/VoucherControllerTests.java
- Controller에서 voucherList 메서드에 대한 테스트 시나리오를 작성하였습니다.
> [2기-C]김산:white_check_mark: Test: Voucher List 에 대한 테스트 시나리오 작성

- src/main/java/com/example/voucher/CommandType.java
- src/main/java/com/example/voucher/VoucherApplication.java
- src/main/java/com/example/voucher/controller/VoucherController.java
- src/main/java/com/example/voucher/dto/VoucherListResponse.java
- src/test/java/com/example/voucher/VoucherApplicationTests.java
* VoucherApplication의 전체 조회 기능 구현이 VoucherApplication 테스트 성공을 위해 작성된 코드와 큰 차이가 없어 하나의 pr로 올립니다!
> [2기-C] 정하영 바우처 전체 조회 기능에 대한 VoucherApplication 테스트와 구현

- src/test/java/com/waterfogsw/voucher/voucher/VoucherControllerTests.java
- 바우처 조회 메서드에 대한 Test 코드를 작성하였습니다.
> [2기-C] 김산 바우처 조회 Test 코드 작성

- mission/src/main/java/org/prgrms/voucher/repository/VoucherMemoryRepository.java
- mission/src/test/java/org/prgrms/voucher/repository/VoucherMemoryRepositoryTest.java
repository findAll 에대한 테스트 코드와 구현을 완료했습니다.
감사합니다!
> [2기-C]유재희 :sparkles: feat : repository findAll 테스트 코드 작성, 구현

- src/main/java/com/waterfogsw/voucher/voucher/controller/VoucherController.java
- src/main/java/com/waterfogsw/voucher/voucher/service/VoucherManageService.java
- src/main/java/com/waterfogsw/voucher/voucher/service/VoucherService.java
- 컨트롤러의 바우처 조회 메서드 프로덕션코드와 Service레이어에서의 일부 구성입니다.
> :sparkles: Feat: 바우처 조회 프로덕션 코드

- src/test/java/com/waterfogsw/voucher/voucher/VoucherServiceTests.java
findAllVoucher 테스트 코드 입니다. 감사합니다!
> [2기-C]: white_check_mark: Test: findAllVoucher 테스트 코드

- src/main/java/com/waterfogsw/voucher/voucher/repository/VoucherMemoryRepository.java
- src/main/java/com/waterfogsw/voucher/voucher/repository/VoucherRepository.java
- src/main/java/com/waterfogsw/voucher/voucher/service/VoucherManageService.java
VoucherService의 findAllVoucher 프로덕션 코드입니다! 
감사합니다!
> [2기-C] 김산 :sparkles: Feat: findAllVoucher 프로덕션 코드

- mission/src/test/java/org/prgrms/voucher/service/VoucherServiceTest.java
PercentDiscountVoucher feature 추가를 위한 서비스 테스트 시나리오 입니다.
어프로브시 테스트코드와 프로덕션 코드의 PercentDiscountVoucher 의 feature 구현 진행하겠습니다!
> [2기-C] 유재희 :white_check_mark: test : PercentDiscountVoucher 서비스 테스트 시나리오

- mission/src/main/java/org/prgrms/voucher/models/PercentDiscountVoucher.java
- mission/src/main/java/org/prgrms/voucher/models/VoucherType.java
- mission/src/test/java/org/prgrms/voucher/service/VoucherServiceTest.java
PercentDiscountVoucher 기능을 테스트코드를 추가하고 구현을 완료했습니다.
감사합니다.
> [2기-C] 유재희:sparkles: feat : PercentDiscountVoucher 추가 구현

- src/main/java/com/waterfogsw/voucher/voucher/repository/VoucherMemoryRepository.java
- src/test/java/com/waterfogsw/voucher/voucher/VoucherRepositoryTests.java
- VoucherRepository의 findAll 메서드에 대한 테스트와 구현입니다.
- repository에 필드값으로 있는 맵에는 직접 접근할수 없어 reflection을 활용해 테스트 코드를 작성하였습니다.
> [2기-C]김산 VoucherRepository의 findAll 메서드에 대한 테스트와 구현입니다.

- src/main/java/kdt/vouchermanagement/domain/voucher/domain/FixedAmountVoucher.java
- src/main/java/kdt/vouchermanagement/domain/voucher/domain/Voucher.java
- src/main/java/kdt/vouchermanagement/domain/voucher/domain/VoucherType.java
- src/main/java/kdt/vouchermanagement/domain/voucher/repository/VoucherIdGenerator.java
- src/main/java/kdt/vouchermanagement/domain/voucher/repository/VoucherMemoryRepository.java
> [2기-C]류영준 - FixedAmountVoucher 저장 프로덕션 코드 구현

- src/main/java/kdt/vouchermanagement/domain/voucher/controller/VoucherConsoleController.java
- src/main/java/kdt/vouchermanagement/domain/voucher/service/VoucherService.java
- src/main/java/kdt/vouchermanagement/domain/voucher/service/VoucherServiceImpl.java
- src/test/java/kdt/vouchermanagement/VoucherConsoleControllerTest.java
바우처 목록 조회 기능 controller 테스트 코드 구현 & 구조 구현하였습니다
.
> [2기-C]류영준 - 바우처 목록 조회 controller 테스트 코드 구현 & 구조 구현

- mission/src/main/java/org/prgrms/voucher/CommandLineApplication.java
- mission/src/main/java/org/prgrms/voucher/Converter.java
- mission/src/main/java/org/prgrms/voucher/io/ConsoleInput.java
- mission/src/main/java/org/prgrms/voucher/io/ConsoleOutput.java
- mission/src/main/java/org/prgrms/voucher/io/Input.java
- mission/src/main/java/org/prgrms/voucher/io/Output.java
어플리케이션 콘솔과 앞단 구조를 생각해보고 구성을 추가해봤습니다.
Input -> Output -> CommandLine App 순으로 구현할 생각입니다.
CommandLineApp은 사용자에게 화면을 띄워주고 입력을 받는 역할을 하며 입력받은 데이터(요청)을 Converter에게 넘겨줍니다. 
Converter는 CommandLineApp에게 받은 사용자의 입력데이터 혹은 요청을 컨트롤러에게 적합한 타입의 데이터로 변환해 전달해줍니다.
콘솔과 컨트롤러를 이어주는 Converter를 마지막에 구현할 계획입니다.
감사합니다.
> [2기-C]유재희 :sparkles: feat : 어플리케이션 프론트 구조 구성

- src/main/java/com/waterfogsw/voucher/console/Command.java
- src/main/java/com/waterfogsw/voucher/console/Console.java
- src/main/java/com/waterfogsw/voucher/console/ConsoleApplication.java
- src/main/java/com/waterfogsw/voucher/console/Input.java
- src/main/java/com/waterfogsw/voucher/console/Output.java
- src/main/java/com/waterfogsw/voucher/global/FrontController.java
- src/main/java/com/waterfogsw/voucher/global/MessageConverter.java
입출력 부분 구조 설계입니다.
- ConsoleApplication은 사용자의 입력을 받으면 FrontController로 입력을 전송합니다.
- FrontController는 MessageConverter를 활용하여 데이터를 DTO로 변환하고, 적절한 Controller의 메서드를 호출합니다.
> [2기-C] 김산 :art: Struct: 입출력 구조 설계

- src/test/java/com/example/voucher/io/OutputTest.java
> [2기-C] 정하영 콘솔 출력 테스트 구현

- src/test/java/com/dojinyou/devcourse/voucherapplication/voucher/VoucherControllerTest.java
> [2기-C] 유도진 - 바우처 컨트롤러 테스트 코드 작성

- src/main/java/kdt/vouchermanagement/domain/voucher/controller/VoucherConsoleController.java
- src/test/java/kdt/vouchermanagement/VoucherConsoleControllerTest.java
> [2기-C]류영준 - 바우처 목록 조회 controller 코드 구현

- src/main/java/com/waterfogsw/voucher/global/VoucherTypeConverter.java
- src/test/java/com/waterfogsw/voucher/voucher/VoucherTypeConverterTests.java
- 기존에 MessageConverter로만 Dto 변환을 하였는데 MessageConverter의 역할이 너무 많은것 같아, 바우처 타입만 Converter해주는 VoucherTypeConverter 따로 만들어 구현하였습니다.
> [2기 - C] 김산 바우처 타입 컨버터 테스트 코드 및 구현

- mission/src/main/java/org/prgrms/voucher/CommandType.java
초기 화면과 명령어들을 나열한 enum 클래스 CommandType을 추가했습니다.
> [2기-C] 유재희:sparkles: feat : Enum CommandType 추가

- src/main/java/kdt/vouchermanagement/domain/voucher/repository/VoucherRepository.java
- src/test/java/kdt/vouchermanagement/VoucherServiceTest.java
바우처 목록 조회 service 테스트 코드 구현 & 구조 구현
> [2기-C]류영준 - 바우처 목록 조회 service 테스트 코드 구현 & 구조 구현

- mission/src/main/java/org/prgrms/voucher/io/ConsoleInput.java
- mission/src/main/java/org/prgrms/voucher/io/ConsoleOutput.java
- mission/src/main/java/org/prgrms/voucher/io/Input.java
- mission/src/main/java/org/prgrms/voucher/io/Output.java
Input, Output 인터페이스와
Console Input ,
Console Output  두 구현체를 구현했습니다.
감사합니다!
> [2기-C] 유재희:sparkles: feat : Input, Output 구현입니다.

- src/main/java/kdt/vouchermanagement/domain/voucher/service/VoucherServiceImpl.java
> [2기-C]류영준 - 바우처 목록 조회 service 프로덕션 코드 구현

- src/main/java/com/waterfogsw/voucher/console/Command.java
- src/main/java/com/waterfogsw/voucher/console/Messages.java
- src/main/java/com/waterfogsw/voucher/global/MessageConverter.java
- src/main/java/com/waterfogsw/voucher/global/RequestMessage.java
- src/main/java/com/waterfogsw/voucher/global/RequestVoucherMessage.java
- src/test/java/com/waterfogsw/voucher/voucher/MessageConverterTests.java
MessageConverter에 대한 테스트 코드입니다.
VoucherType에 대한 검증은 VoucherTypeConverter가 하기 때문에 MessageConverter에서는 진행하지 않았습니다.
> [2기 - C] 김산 MessageConverter 테스트코드 및 구현

- src/main/java/kdt/vouchermanagement/domain/voucher/domain/PercentDiscountVoucher.java
- src/main/java/kdt/vouchermanagement/domain/voucher/domain/VoucherType.java
PercentAmountVoucher 생성 프로덕션 코드 구현입니다.
PercentAmountVoucher 생성할 때 유효성 검사하는 것은 리팩토링 때 해보도록 하겠습니다!
> [2기-C]류영준 - PercentAmountVoucher 생성 프로덕션 코드 구현

- src/main/java/com/dojinyou/devcourse/voucherapplication/voucher/VoucherController.java
- src/main/java/com/dojinyou/devcourse/voucherapplication/voucher/domain/FixedAmountVoucher.java
- src/main/java/com/dojinyou/devcourse/voucherapplication/voucher/domain/PercentAmountVoucher.java
- src/main/java/com/dojinyou/devcourse/voucherapplication/voucher/domain/Voucher.java
- src/main/java/com/dojinyou/devcourse/voucherapplication/voucher/domain/VoucherMapper.java
- src/test/java/com/dojinyou/devcourse/voucherapplication/voucher/VoucherControllerTest.java
- src/test/java/com/dojinyou/devcourse/voucherapplication/voucher/VoucherServiceTest.java
1. dto 변환 역할 위임(service -> controller)
2. 역할 위임에 따른 controller test 코드 수정
3. 역할 위임에 따른 controller 구현 코드 수정
4. 역할 위임에 따른 service test 코드 수정
> [2기-C] 유도진 - Service Test 코드 작성 및  dto 변환 역할 위임 반영

- src/main/java/com/example/voucher/VoucherApplication.java
- src/main/java/com/example/voucher/domain/voucher/repository/VoucherMemoryRepository.java
- src/test/java/com/example/voucher/VoucherApplicationTests.java
> 정하영 - 프롬프트 출력 기능 테스트와 구현

- src/main/java/com/dojinyou/devcourse/voucherapplication/voucher/VoucherService.java
> [2기-C] 유도진 - Voucher Service 구현

- build.gradle
- src/main/java/com/example/voucher_manager/application/RunApplication.java
- src/main/java/com/example/voucher_manager/domain/customer/BlacklistCustomerRepository.java
- src/main/java/com/example/voucher_manager/domain/customer/CsvBlacklistCustomerRepository.java
- src/main/java/com/example/voucher_manager/domain/customer/Customer.java
- src/main/java/com/example/voucher_manager/domain/customer/CustomerRepository.java
- src/main/java/com/example/voucher_manager/domain/customer/CustomerService.java
- src/main/java/com/example/voucher_manager/domain/customer/JdbcCustomerRepository.java
- src/main/java/com/example/voucher_manager/domain/voucher/FileVoucherRepository.java
- src/main/java/com/example/voucher_manager/domain/voucher/FixedAmountVoucher.java
- src/main/java/com/example/voucher_manager/domain/voucher/JdbcVoucherRepository.java
- src/main/java/com/example/voucher_manager/domain/voucher/MemoryVoucherRepository.java
- src/main/java/com/example/voucher_manager/domain/voucher/PercentDiscountVoucher.java
- src/main/java/com/example/voucher_manager/domain/voucher/Voucher.java
- src/main/java/com/example/voucher_manager/domain/voucher/VoucherRepository.java
- src/main/java/com/example/voucher_manager/domain/voucher/VoucherService.java
- src/main/java/com/example/voucher_manager/domain/voucher/VoucherType.java
- src/main/java/com/example/voucher_manager/io/CommandOperator.java
- src/main/java/com/example/voucher_manager/io/CommandType.java
- src/main/java/com/example/voucher_manager/io/Console.java
- src/main/java/com/example/voucher_manager/io/InputValidator.java
- src/main/resources/application.yaml
- src/main/resources/customer_blacklist.csv
- src/test/java/com/example/voucher_manager/domain/customer/JdbcCustomerRepositoryTest.java
- src/test/java/com/example/voucher_manager/domain/voucher/JdbcVoucherRepositoryTest.java
- src/test/java/com/example/voucher_manager/domain/voucher/MemoryVoucherRepositoryTest.java
- src/test/java/com/example/voucher_manager/io/InputValidatorTest.java
- src/test/resources/init.sql
- src/test/resources/logback.xml
바우처 관리 서비스 제작
**(기본)** **바우처 관리 애플리케이션**
- 가능한 많은 단위 테스트코드를 작성하려고 노력해보세요.
- 엣지 케이스(예외 케이스)를 고려해서 작성해주세요.
- Hamcrest 의 메쳐들을 다양하게 작성해보고 익숙해져 보세요.
- customers 테이블 정의 및 추가
- CustomerRepository 추가 및 JdbcTemplate을 사용해서 구현
- 바우처에 엔터티에 해당하는 vouchers 테이블을 한번 정의해보세요.
- 바우처 레포지토리를 만들어보세요. (JdbcTemplate을 사용해서 구현)
- 기존의 파일에서 바우처를 관리한 것을 vouchers 테이블을 통해서 CRUD가 되게 해보세요.
**(심화)** **바우처 지갑을 만들어보세요.**
- Wallet의 요구사항을 고려했을 때 Voucher가 사전에 특정 수량 할당되고, 추후에 고객에게 배정되는 형식이라고 생각하고 개발했습니다. 소비자의 관점에서는 당연히 고객이 바우처의 리스트 형태를 저장하고 있는 것이 맞아보이는데.. 이부분에 대해 어떻게 생각하시는지 궁금합니다..! 이렇게도 작성이 가능할지.. 방향성을 잡아주시면 고치도록 하겠습니다.
- 기존에 사용하던 FileVoucherRepository의 경우에는, 이번 과제를 기점으로 사용하지 않게 되는데, 인터페이스에 여러가지 쿼리를 처리하기 위한 함수들을 추가하게 되면서 사용하지 않는 FileVoucherRepository에도 갖가지 코드들을 오버라이딩 해줘야하는 경우가 생겼습니다. 현재는 우선 추가만 해두고 작동하지는 않는 형태지만 이럴때 어떤식으로 개선할지 …
> [2기-P] 정윤오 SpringBoot Part2 Weekly Mission 코드리뷰 요청드립니다.

- src/main/java/com/dojinyou/devcourse/voucherapplication/voucher/MemoryVoucherRepository.java
- src/test/java/com/dojinyou/devcourse/voucherapplication/VoucherApplicationTest.java
- src/test/java/com/dojinyou/devcourse/voucherapplication/view/ConsoleViewTest.java
- src/test/java/com/dojinyou/devcourse/voucherapplication/voucher/MemoryVoucherRepositoryTest.java
- src/test/java/com/dojinyou/devcourse/voucherapplication/voucher/VoucherControllerTest.java
- src/test/java/com/dojinyou/devcourse/voucherapplication/voucher/VoucherServiceTest.java
1. MemoryVoucherRepository 관련 테스트 구현
> [2기-C] 유도진 - MemoryVoucherRepository 관련 테스트 코드 작성

- src/main/java/com/example/voucher/CommandType.java
> [2기-C] 정하영 - 명령어 타입 구현

- src/main/java/kdt/vouchermanagement/global/io/ConsoleInput.java
- src/main/java/kdt/vouchermanagement/global/io/ConsoleOutput.java
- src/main/java/kdt/vouchermanagement/global/response/Response.java
- src/main/java/kdt/vouchermanagement/global/view/CommandMessage.java
- src/main/java/kdt/vouchermanagement/global/view/ConsoleDispatcher.java
- src/main/resources/application.properties
- src/main/resources/application.yaml
- src/test/java/kdt/vouchermanagement/ConsoleOutputTest.java
* 애플리케이션 출력을 위한 프로덕션 코드를 구현하였습니다.
* application.prorperties를 삭제하고 profile 설정을 위하여 application.yaml을 생성하였습니다.
> [2기-C]류영준 - 애플리케이션 출력 프로덕션 코드 구현

- src/main/java/com/dojinyou/devcourse/voucherapplication/voucher/MemoryVoucherRepository.java
1. MemoryVoucherRepository 관련 create 기능 구현
> [2기-C] 유도진 - MemoryVoucherRepository

- src/main/java/com/example/voucher/VoucherApplication.java
- src/main/java/com/example/voucher/domain/voucher/FixedAmountVoucher.java
- src/main/java/com/example/voucher/domain/voucher/PercentDiscountVoucher.java
- src/main/java/com/example/voucher/domain/voucher/Voucher.java
- src/main/java/com/example/voucher/domain/voucher/VoucherType.java
- src/main/java/com/example/voucher/domain/voucher/repository/VoucherFileRepository.java
- src/main/java/com/example/voucher/domain/voucher/repository/VoucherIdGenerator.java
- src/main/java/com/example/voucher/domain/voucher/repository/VoucherMemoryRepository.java
- src/main/java/com/example/voucher/exception/ErrorMessage.java
- src/main/java/com/example/voucher/util/FileUtils.java
- src/main/resources/application.properties
- src/test/java/com/example/voucher/domain/repository/VoucherFileRepositoryTest.java
- src/test/java/com/example/voucher/domain/repository/VoucherMemoryRepositoryTest.java
- src/test/java/com/example/voucher/util/FileUtilsTest.java
* File 처리를 담당하는 FileUtils를 생성하였습니다.
* VoucherId 생성 기능을 담당하는 VoucherIdGenerator를 생성하였습니다.
* 바우처를 저장할 때 csv형식에 맞게 저장되도록 FixedAmountVoucher, PercentDiscountVoucher의 toString()을 오버라이딩하였습니다.
* toString() 을 오버라이딩하면서 Voucher에 equals(), hashcode()도 오버라이딩하였습니다.
* FileUtils 또는 VoucherFileRepository에서 예외가 발생 할 경우 VoucherApplication에서 처리할수 있도록 VoucherApplication에 try-catch 코드를 추가하였습니다.
* ErrorMessage에 파일 관련 예외 메시지를 추가하였습니다.
* 1주차 남은 코드 구현
* - [ ] EXIT기능 구현
* - [ ] 로그 남기기
* - [ ] 예외 발생시 코드 수정
> [2기-C] 정하영 - VoucherFileRepository 구현

- build.gradle
- src/main/java/com/waterfogsw/voucher/utils/FileUtils.java
- src/main/java/com/waterfogsw/voucher/voucher/controller/VoucherController.java
- src/main/java/com/waterfogsw/voucher/voucher/domain/FixedAmountVoucher.java
- src/main/java/com/waterfogsw/voucher/voucher/domain/PercentDiscountVoucher.java
- src/main/java/com/waterfogsw/voucher/voucher/domain/Voucher.java
- src/main/java/com/waterfogsw/voucher/voucher/dto/ResponseStatus.java
- src/main/java/com/waterfogsw/voucher/voucher/repository/VoucherFileRepository.java
- src/main/java/com/waterfogsw/voucher/voucher/repository/VoucherMemoryRepository.java
- src/main/resources/application.yaml
- src/test/java/com/waterfogsw/voucher/voucher/VoucherFileRepositoryTests.java
- jackson라이브러리를 활용해 바우처 객체를 .json파일로 직렬화하여 파일 레포지토리를 구현하였습니다.
- VoucherFileRepository의 생성자에 디렉토리 초기화 함수를 포함시켜 실행할때마다 디렉토리가 초기화되도록 구현하였습니다.
- 프로퍼티를 적용하여 조회되는 빈이 2개이상일 경우에 대한 문제를 해결하였습니다.
-  VoucherRepository에 대해 VoucherMemoryRepository, VoucherFileRepository 두개의 구현체가 존재하여 발생합니다.
- 파일을 저장할 위치를 프로퍼티 속성을 통해 전달하도록 하였습니다.
> [2기-C] 김산 바우처 파일 레포지토리 테스트 코드 및 구현입니다.

- mission/src/test/java/org/prgrms/voucher/repository/VoucherJdbcRepositoryTest.java
Jdbc 레포지토리 테스트 시나리오입니다.
어프로브시 테스트코드와 프로덕션 코드 구현체를 다음 PR에 올리겠습니다!!!
감사합니다.
> [2기-C] 유재희 :white_check_mark: test : jdbcRepo save, findAll 테스트 시나리오

- mission/build.gradle
- mission/src/main/java/org/prgrms/voucher/repository/VoucherJdbcRepository.java
- mission/src/main/resources/application.yaml
- mission/src/main/resources/schema.sql
- mission/src/test/java/org/prgrms/voucher/repository/VoucherJdbcRepositoryTest.java
VoucherJdbcRepository의 테스트코드와 프로덕션 코드입니다.
voucher의 ID는 database의 auto_increment 속성으로 관리가 됩니다.
save 진행시 id가 null이면 새로 생성된 바우처로 판단해 auto_increment를 적용해 id를 부여하고 저장합니다.
id가 null이 아니라면 업데이트를 진행할 예정인데 update기능 추가 시 추가 구현하도록 하겠습니다.
만약 db에 저장되어있지 않는 id가 save의 인자로 넘어온다면 알 수 없는 id로 판단해 예외를 반환할 계획입니다.
> [2기-C] 유재희 jdbcRepository 테스트코드 작성, 프로덕션 코드 구현

- mission/src/main/java/org/prgrms/voucher/dto/VoucherDto.java
- mission/src/main/java/org/prgrms/voucher/models/FixedAmountVoucher.java
- mission/src/main/java/org/prgrms/voucher/models/PercentDiscountVoucher.java
- mission/src/main/java/org/prgrms/voucher/models/Voucher.java
- mission/src/main/java/org/prgrms/voucher/models/VoucherType.java
- mission/src/main/java/org/prgrms/voucher/repository/VoucherFileRepository.java
- mission/src/main/java/org/prgrms/voucher/repository/VoucherJdbcRepository.java
- mission/src/main/java/org/prgrms/voucher/repository/VoucherMemoryRepository.java
- mission/src/main/resources/application.yaml
- mission/src/main/resources/schema.sql
- mission/src/test/java/org/prgrms/voucher/controller/VoucherControllerTest.java
- mission/src/test/java/org/prgrms/voucher/repository/VoucherJdbcRepositoryTest.java
- mission/src/test/java/org/prgrms/voucher/repository/VoucherMemoryRepositoryTest.java
- mission/src/test/java/org/prgrms/voucher/service/VoucherServiceTest.java
Voucher 도메인 생성시간필드 추가에 따른 변경사항입니다.
- 필드 추가
- 생성자에 created 파라미터 추가
- 각 Repository 저장 및 생성시 필드 추가
- 테스트 코드에서 바우처 생성시 필드 추가
- 데이터 베이스에 created_at 추가
이상입니다!
> [2기-C]유재희 :white_check_mark: 바우처 createdAt 필드 추가에 따른 변경

- build.gradle
- src/main/java/com/example/voucher/domain/voucher/repository/VoucherFileRepository.java
- src/main/java/com/example/voucher/domain/voucher/repository/VoucherJdbcRepository.java
- src/main/resources/schema.sql
- src/test/java/com/example/voucher/domain/repository/VoucherJdbcRepositoryTest.java
- src/test/resources/schema.sql
* 구현을 위해 mysql, spring-jdbc 의존성을 추가하였습니다.
* 테스트에서 h2 in memory로 테스트 하기 위해 h2 의존성을 추가하였습니다.
* 바우처에 대한 테이블 생성 스키마를 schema.sql로 추가하였습니다.
* VoucherJdbcRepository 테스트와 구현을 추가하였습니다.
> [2기-C] 정하영 VoucherJdbcRepository 테스트와 구현입니다.

- build.gradle
- src/main/java/kdt/vouchermanagement/domain/voucher/domain/Voucher.java
- src/main/java/kdt/vouchermanagement/domain/voucher/repository/VoucherJdbcRepository.java
- src/main/resources/application.yaml
- src/main/resources/schema.sql
- src/test/java/kdt/vouchermanagement/VoucherJdbcRepositoryTest.java
* Voucher 도메인 create 기능과 list 기능에 대한 JdbcTemplate 레포지토리를 구현하였습니다.
> [2기-C]류영준 - Voucher create, list JdbcTemplate 연동 테스트 코드 & 프로덕션 코드 구현

- build.gradle
- src/main/java/kdt/vouchermanagement/domain/voucher/controller/ControllerAdvice.java
- src/main/java/kdt/vouchermanagement/domain/voucher/controller/VoucherApiController.java
- src/main/java/kdt/vouchermanagement/domain/voucher/dto/VoucherRequest.java
- src/test/java/kdt/vouchermanagement/VoucherApiControllerTest.java
Voucher Create 기능과 모든 바우처 조회인 List 기능을 구현하였습니다.
> [2기-C]류영준 Voucher Create, List 기능 테스트 코드 & 프로덕션 코드 구현

- src/main/java/kdt/vouchermanagement/domain/voucher/domain/FixedAmountVoucher.java
- src/main/java/kdt/vouchermanagement/domain/voucher/domain/PercentDiscountVoucher.java
- src/main/java/kdt/vouchermanagement/domain/voucher/domain/Voucher.java
- src/main/java/kdt/vouchermanagement/domain/voucher/domain/VoucherType.java
- src/main/java/kdt/vouchermanagement/domain/voucher/repository/VoucherFileRepository.java
- src/main/java/kdt/vouchermanagement/domain/voucher/repository/VoucherJdbcRepository.java
- src/main/java/kdt/vouchermanagement/domain/voucher/repository/VoucherMemoryRepository.java
- src/main/resources/schema.sql
- src/test/java/kdt/vouchermanagement/ConsoleOutputTest.java
- src/test/java/kdt/vouchermanagement/VoucherApiControllerTest.java
- src/test/java/kdt/vouchermanagement/VoucherConsoleControllerTest.java
- src/test/java/kdt/vouchermanagement/VoucherJdbcRepositoryTest.java
- src/test/java/kdt/vouchermanagement/VoucherServiceTest.java
* Voucher 도메인 createdAt, updatedAt 필드 추가에 따른 테스트 코드 수정과 프로덕션 코드 수정입니다.
* Voucher 테이블에 created_at, updated_at 컬럼을 추가하였습니다.
> [2기-C]류영준 - Voucher 도메인 필드 추가

- mission/build.gradle
- mission/src/main/java/org/prgrms/voucher/CommandLineApplication.java
- mission/src/main/java/org/prgrms/voucher/controller/VoucherWebController.java
- mission/src/main/java/org/prgrms/voucher/controller/console/VoucherController.java
- mission/src/main/java/org/prgrms/voucher/controller/web/VoucherWebController.java
- mission/src/main/java/org/prgrms/voucher/dto/VoucherDto.java
- mission/src/test/java/org/prgrms/voucher/controller/VoucherControllerTest.java
- mission/src/test/java/org/prgrms/voucher/controller/VoucherWebControllerTest.java
바우처 create , list 기능의 REST API 컨트롤러를 테스트, 구현하였습니다
Vaild 어노테이션을 Request Dto에 적용했습니다!
RestController를 만들면서 기존의 컨트롤러 패키지 구조를 변경하였습니다! 
감사합니다!
> [2기-C] 유재희 :sparkles: feat : create, list 기능 RestController 구현, Test

- src/main/java/com/example/voucher/domain/voucher/FixedAmountVoucher.java
- src/main/java/com/example/voucher/domain/voucher/PercentDiscountVoucher.java
- src/main/java/com/example/voucher/domain/voucher/Voucher.java
- src/main/java/com/example/voucher/domain/voucher/VoucherType.java
- src/main/java/com/example/voucher/domain/voucher/repository/VoucherFileRepository.java
- src/main/java/com/example/voucher/domain/voucher/repository/VoucherJdbcRepository.java
- src/main/java/com/example/voucher/domain/voucher/repository/VoucherMemoryRepository.java
- src/main/java/com/example/voucher/dto/VoucherResponse.java
- src/main/java/com/example/voucher/service/voucher/VoucherServiceImpl.java
- src/main/resources/schema.sql
- src/test/java/com/example/voucher/api/VoucherRestControllerTest.java
- src/test/java/com/example/voucher/domain/repository/VoucherFileRepositoryTest.java
- src/test/java/com/example/voucher/domain/repository/VoucherMemoryRepositoryTest.java
- src/test/resources/schema.sql
* 검색 조건에 따른 api 구현을 위해서 Voucher에 createdAt, updatedAt을 추가하고 테이블에도 컬럼을 추가하였습니다.
> [2기-C] 정하영 - Voucher 필드 추가 구현입니다.

- mission/src/main/java/org/prgrms/voucher/dto/VoucherDto.java
- mission/src/main/java/org/prgrms/voucher/models/FixedAmountVoucher.java
- mission/src/main/java/org/prgrms/voucher/models/PercentDiscountVoucher.java
- mission/src/main/java/org/prgrms/voucher/models/Voucher.java
- mission/src/main/java/org/prgrms/voucher/models/VoucherType.java
- mission/src/main/java/org/prgrms/voucher/repository/VoucherFileRepository.java
- mission/src/main/java/org/prgrms/voucher/repository/VoucherJdbcRepository.java
- mission/src/main/java/org/prgrms/voucher/repository/VoucherMemoryRepository.java
- mission/src/main/resources/schema.sql
- mission/src/test/java/org/prgrms/voucher/controller/VoucherControllerTest.java
- mission/src/test/java/org/prgrms/voucher/controller/VoucherWebControllerTest.java
- mission/src/test/java/org/prgrms/voucher/repository/VoucherJdbcRepositoryTest.java
- mission/src/test/java/org/prgrms/voucher/repository/VoucherMemoryRepositoryTest.java
- mission/src/test/java/org/prgrms/voucher/service/VoucherServiceTest.java
Voucher도메인의 필드 updatedAt 추가에 따른 변경입니다!
- voucherResponseDto 수정
- voucher 생성자에 updatedAt 추가
- 테스트시 바우처 생성에 updatedAt 추가
- 각 repository 저장, 생성에 updatedAt 추가 
이상입니다! 
감사합니다!
> [2기-C] 유재희:white_check_mark: add : updatedAt 추가에 따른 변경

- build.gradle
- src/main/java/com/waterfogsw/voucher/utils/FileUtils.java
- src/main/java/com/waterfogsw/voucher/voucher/domain/FixedAmountVoucher.java
- src/main/java/com/waterfogsw/voucher/voucher/domain/PercentDiscountVoucher.java
- src/main/java/com/waterfogsw/voucher/voucher/domain/Voucher.java
- src/main/java/com/waterfogsw/voucher/voucher/dto/ResponseVoucherDto.java
- src/main/java/com/waterfogsw/voucher/voucher/repository/VoucherJdbcRepository.java
- src/test/java/com/waterfogsw/voucher/voucher/FrontControllerTests.java
- src/test/java/com/waterfogsw/voucher/voucher/VoucherRestControllerTests.java
Voucher 도메인에 createdAt, updatedAt 필드를 추가하였습니다
jackson라이브러리에서 LocalDateTime이 매핑되지 않는 문제가 있어서 jackson-datatype-jsr310 모듈을 추가하였습니다
> [2기-C] 김산 createdAt, updatedAt 필드 추가

- mission/src/main/java/org/prgrms/voucher/controller/web/VoucherWebController.java
- mission/src/main/java/org/prgrms/voucher/exception/GlobalExceptionHandler.java
- mission/src/main/java/org/prgrms/voucher/models/PercentDiscountVoucher.java
- mission/src/main/java/org/prgrms/voucher/repository/VoucherFileRepository.java
- mission/src/main/java/org/prgrms/voucher/repository/VoucherJdbcRepository.java
- mission/src/main/java/org/prgrms/voucher/repository/VoucherMemoryRepository.java
- mission/src/main/java/org/prgrms/voucher/repository/VoucherRepository.java
- mission/src/main/java/org/prgrms/voucher/service/VoucherService.java
- mission/src/test/java/org/prgrms/voucher/controller/VoucherWebControllerTest.java
- mission/src/test/java/org/prgrms/voucher/repository/VoucherJdbcRepositoryTest.java
- mission/src/test/java/org/prgrms/voucher/service/VoucherServiceTest.java
- 바우처 삭제
- 바우처 삭제 기능을 Controller, Service, Repository 순서대로 구현했습니다.
- 테스트 코드를 작성했습니다.
- 바우처 아이디 조회
- 바우처 아이디 조회 기능을 Controller, Service, Repository순서대로 구현했습니다.
- 테스트 코드를 작성했습니다.
- 바우처 날짜별, 타입별 조회
- 바우처 조건 조회기능을 Controller 단에서 findAll을 이용해 구현했습니다.
- 테스트 코드를 작성했습니다.
- 예외 처리를 위한 GlobalExceptionHandler를 추가했습니다.
- 기존에 protect였던 PercentDiscountVoucher의 생성자를 public으로 수정했습니다.
이상입니다
감사합니다!
> [2기-C] 유재희:sparkles: fix : findById, Delete, findByType,Date구현 및 테스트

- src/main/java/kdt/vouchermanagement/domain/voucher/controller/VoucherApiController.java
- src/main/java/kdt/vouchermanagement/domain/voucher/domain/Voucher.java
- src/main/java/kdt/vouchermanagement/domain/voucher/repository/VoucherFileRepository.java
- src/main/java/kdt/vouchermanagement/domain/voucher/repository/VoucherJdbcRepository.java
- src/main/java/kdt/vouchermanagement/domain/voucher/repository/VoucherMemoryRepository.java
- src/main/java/kdt/vouchermanagement/domain/voucher/repository/VoucherRepository.java
- src/main/java/kdt/vouchermanagement/domain/voucher/service/VoucherService.java
- src/main/java/kdt/vouchermanagement/domain/voucher/service/VoucherServiceImpl.java
- src/test/java/kdt/vouchermanagement/VoucherApiControllerTest.java
- src/test/java/kdt/vouchermanagement/VoucherJdbcRepositoryTest.java
- src/test/java/kdt/vouchermanagement/VoucherServiceTest.java
* Voucher 삭제(delete), id로 조회(findById), 생성날짜로 조회(findByDate), 할인타입으로 조회(findByType) 기능 테스트 코드와 프로덕션 코드를 구현하였습니다.
* repository는 jdcbTemplate으로만 구현하고, FileRepository와 MemoryRepository는 null로 처리하였습니다.
> [2기-C]류영준 - Voucher 삭제, id로 조회, 생성날짜로 조회, 할인타입으로 조회 기능 테스트 코드 & 프로덕션 코드 구현

- src/main/java/com/example/voucher/controller/api/CustomerRestController.java
- src/main/java/com/example/voucher/domain/customer/Customer.java
- src/main/java/com/example/voucher/domain/customer/repository/CustomerJdbcRepository.java
- src/main/java/com/example/voucher/domain/customer/repository/CustomerRepository.java
- src/main/java/com/example/voucher/dto/CustomerRequest.java
- src/main/java/com/example/voucher/dto/CustomerResponse.java
- src/main/java/com/example/voucher/io/ConsoleReader.java
- src/main/java/com/example/voucher/io/ConsoleWriter.java
- src/main/java/com/example/voucher/service/customer/CustomerService.java
- src/main/java/com/example/voucher/service/customer/CustomerServiceImpl.java
- src/main/resources/schema.sql
- src/test/java/com/example/voucher/api/CustomerRestControllerTest.java
- src/test/java/com/example/voucher/domain/customer/repository/CustomerJdbcRepositoryTest.java
- src/test/java/com/example/voucher/service/customer/CustomerServiceTest.java
- src/test/resources/schema.sql
* 불필요한 파일 삭제
-> main에 이미 존재하는 스키마 파일이 test에 굳이 또 있을 필요가 없어 삭제하였습니다.
* Customer 기능 구현
-> findAll, save, deleteById 구현했습니다. 
* 응답 메시지 잘못 출력 하던 부분 수정
> [2기-C] 정하영 - Customer 기능 구현

- .gitignore
- build.gradle
- src/main/java/com/dojinyou/devcourse/voucherapplication/voucher/VoucherJdbcRepository.java
- src/main/java/com/dojinyou/devcourse/voucherapplication/voucher/VoucherService.java
- src/main/java/com/dojinyou/devcourse/voucherapplication/voucher/domain/VoucherMapper.java
- src/main/resources/application.properties
- src/main/resources/schema.sql
- src/test/java/com/dojinyou/devcourse/voucherapplication/voucher/VoucherControllerTest.java
- src/test/java/com/dojinyou/devcourse/voucherapplication/voucher/VoucherJdbcRepositoryTest.java
- src/test/java/com/dojinyou/devcourse/voucherapplication/voucher/VoucherServiceTest.java
1. VoucherJdbcRespository 관련 테스트 구현
2. VoucherJdbcRespository 구현
> [2기-C] 유도진 - jdbc repository 테스트 코드 작성 및 기능 구현

- mission/src/main/java/org/prgrms/voucher/controller/web/CustomerWebController.java
- mission/src/main/java/org/prgrms/voucher/dto/CustomerRequestDto.java
- mission/src/main/java/org/prgrms/voucher/dto/CustomerResponseDto.java
- mission/src/main/java/org/prgrms/voucher/models/Customer.java
- mission/src/main/java/org/prgrms/voucher/repository/CustomerJdbcRepository.java
- mission/src/main/java/org/prgrms/voucher/repository/CustomerRepository.java
- mission/src/main/java/org/prgrms/voucher/service/CustomerService.java
- mission/src/test/java/org/prgrms/voucher/controller/CustomerWebControllerTest.java
- mission/src/test/java/org/prgrms/voucher/repository/CustomerJdbcRepositoryTest.java
- mission/src/test/java/org/prgrms/voucher/service/CustomerServiceTest.java
Customer 도메인 추가와  생성, 조회, 삭제 기능을 추가했습니다!
감사합니다.
> [2기-C]유재희 Customer 도메인 추가 , 생성, 조회, 삭제기능 구현, 테스트

- build.gradle
- src/main/java/com/waterfogsw/voucher/customer/controller/CustomerApiController.java
- src/main/java/com/waterfogsw/voucher/customer/controller/dto/CustomerAddRequest.java
- src/main/java/com/waterfogsw/voucher/customer/controller/dto/CustomerResponse.java
- src/main/java/com/waterfogsw/voucher/customer/model/Customer.java
- src/main/java/com/waterfogsw/voucher/customer/repository/CustomerJdbcRepository.java
- src/main/java/com/waterfogsw/voucher/customer/repository/CustomerRepository.java
- src/main/java/com/waterfogsw/voucher/customer/service/CustomerDefaultService.java
- src/main/java/com/waterfogsw/voucher/customer/service/CustomerService.java
- src/main/java/com/waterfogsw/voucher/global/ControllerAdvice.java
- src/test/java/com/waterfogsw/voucher/customer/controller/CustomerApiControllerTest.java
- src/test/java/com/waterfogsw/voucher/customer/repository/CustomerJdbcRepositoryTest.java
- src/test/java/com/waterfogsw/voucher/customer/service/CustomerDefaultServiceTest.java
- src/test/java/com/waterfogsw/voucher/voucher/VoucherRestControllerTests.java
- src/test/resources/sql/customerTestTableInit.sql
- src/test/resources/sql/customerTestTableTearDown.sql
- addCustomer, findAll, findById, deleteCustomer 기능을 구현 및 테스트 코드 작성하였습니다.
> [2기-C] 김산 Customer 도메인 기능 구현

- src/main/java/com/dojinyou/devcourse/voucherapplication/Response.java
- src/main/java/com/dojinyou/devcourse/voucherapplication/voucher/VoucherJdbcRepository.java
- src/main/java/com/dojinyou/devcourse/voucherapplication/voucher/domain/FixedAmount.java
- src/main/java/com/dojinyou/devcourse/voucherapplication/voucher/domain/FixedAmountVoucher.java
- src/main/java/com/dojinyou/devcourse/voucherapplication/voucher/domain/PercentAmount.java
- src/main/java/com/dojinyou/devcourse/voucherapplication/voucher/domain/PercentAmountVoucher.java
- src/main/java/com/dojinyou/devcourse/voucherapplication/voucher/domain/Voucher.java
- src/main/java/com/dojinyou/devcourse/voucherapplication/voucher/domain/VoucherAmount.java
- src/main/java/com/dojinyou/devcourse/voucherapplication/voucher/domain/VoucherMapper.java
- src/main/java/com/dojinyou/devcourse/voucherapplication/voucher/dto/VoucherRequest.java
- src/main/java/com/dojinyou/devcourse/voucherapplication/voucher/dto/VoucherResponse.java
- src/main/java/com/dojinyou/devcourse/voucherapplication/voucher/entity/FixedAmountVoucherEntity.java
- src/main/java/com/dojinyou/devcourse/voucherapplication/voucher/entity/PercentAmountVoucherEntity.java
- src/main/java/com/dojinyou/devcourse/voucherapplication/voucher/entity/VoucherEntity.java
- src/test/java/com/dojinyou/devcourse/voucherapplication/voucher/VoucherControllerTest.java
- src/test/java/com/dojinyou/devcourse/voucherapplication/voucher/VoucherFileRepositoryTest.java
- src/test/java/com/dojinyou/devcourse/voucherapplication/voucher/VoucherJdbcRepositoryTest.java
- src/test/java/com/dojinyou/devcourse/voucherapplication/voucher/VoucherMemoryRepositoryTest.java
- src/test/java/com/dojinyou/devcourse/voucherapplication/voucher/VoucherServiceTest.java
1. createdAt, updatedAt field 추가 및 관련 변경사항 반영
2. List type reponse 출력 함수 수정
> [2기-C] 유도진 - createdAt, updatedAt field 추가

- .gitignore
- build.gradle
- src/main/java/org/programmers/voucher/VoucherApplication.java
- src/main/java/org/programmers/voucher/config/VoucherAppConfiguration.java
- src/main/java/org/programmers/voucher/controller/VoucherController.java
- src/main/java/org/programmers/voucher/controller/VoucherRunner.java
- src/main/java/org/programmers/voucher/domain/Customer.java
- src/main/java/org/programmers/voucher/domain/VoucherType.java
- src/main/java/org/programmers/voucher/io/ConsoleInput.java
- src/main/java/org/programmers/voucher/io/ConsoleOutput.java
- src/main/java/org/programmers/voucher/io/Input.java
- src/main/java/org/programmers/voucher/io/Output.java
- src/main/java/org/programmers/voucher/repository/CustomerJdbcRepository.java
- src/main/java/org/programmers/voucher/repository/CustomerRepository.java
- src/main/java/org/programmers/voucher/repository/JdbcUtils.java
- src/main/java/org/programmers/voucher/repository/MemoryVoucherRepository.java
- src/main/java/org/programmers/voucher/repository/VoucherRepository.java
- src/main/java/org/programmers/voucher/service/VoucherService.java
- src/main/java/org/programmers/voucher/util/Command.java
- src/main/java/org/programmers/voucher/util/IllegalCommandException.java
- src/main/java/org/programmers/voucher/util/IllegalVoucherTypeException.java
- src/main/resources/application.yaml
- src/main/resources/logback.xml
- src/main/resources/schema.sql
- src/test/java/org/programmers/voucher/repository/VoucherRepositoryTest.java
- src/test/java/org/programmers/voucher/service/VoucherServiceTest.java
- 코드리뷰 피드백을 기반으로 리팩토링을 진행했습니다
- 전에 완성하지 못했던 Logback 설정까지 완료했습니다.
- 전반적인 구조를 거의 통째로 뜯어고쳤습니다.
- 3-layered-architecture를 최대한 만족하도록 변경하였습니다.
- configuration 대신 annotation 기반으로 컴포넌트 스캔이 일어날 수 있도록 변경하였습니다.
- 역할에 대해서 고민하면서 예외 처리 구조를 변경해 보았습니다.
- 조건문의 뎁스를 최대한 줄이면서 단일 책임을 보장하기 위해 노력해 보았습니다.
- 바우처 별 할인 수치를 입력받을 수 있도록 변경했습니다.
- logback 설정을 진행하였습니다.
- 전반적인 구조를 완전 처음부터 다시 생각해보느라 시간이 좀 걸린 것 같습니다. 
- 가능한 한 객체지향적으로 개발하기 위해 노력해 봤는데 아직 좀 어려운 부분이 있네요... 그래도 생각이 많이 전환된 것 같습니다. 덜 객체지향적인 부분이 있다면, 마구마구 지적해주시면 감사하겠습니다. 생각의 변화가 꾸준히 일어나고 있는 것 같네요.
- log를 설정할 때, debug/info/warn/error 수준을 어느 기준으로 잡아야 할지 설정하는 것도 조금 어려운 것 같네요... 의견 주시면 감사하겠습니다.
- 빠르게 위클리 미션 2번으로 넘어가서 작업 진행하도록 하겠습니다!
> [2기-P] 김진욱 Weekly Mission 1번 리팩토링 완료본입니다.

- .gitignore
- mvnw
- mvnw.cmd
- pom.xml
- src/main/java/org/prgrms/kdt/CommandLineApplication.java
- src/main/java/org/prgrms/kdt/VoucherController.java
- src/main/java/org/prgrms/kdt/VoucherRunner.java
- src/main/java/org/prgrms/kdt/exceptions/WrongSelectException.java
- src/main/java/org/prgrms/kdt/io/Console.java
- src/main/java/org/prgrms/kdt/io/IOManager.java
- src/main/java/org/prgrms/kdt/io/OutputConstant.java
- src/main/java/org/prgrms/kdt/utils/SelectType.java
- src/main/java/org/prgrms/kdt/utils/VoucherAppManager.java
- src/test/java/org/prgrms/kdt/CommandLineApplicationTests.java
**(기본) 바우처 관리 애플리케이션**
* Maven / Gradle 로 프로젝트 구성
* 스프링부트 애플리케이션으로 만든다. 프로그램이 시작하면 다음과 같이 지원가능한 명령어를 알려준다.
```bash
=== Voucher Program ===
Type **exit** to exit the program.
Type **create** to create a new voucher.
Type **list** to list all vouchers.
```
- create / list 커맨드를 지원한다.
- create 커맨드를 통해 바우처를 생성할수 있다. (FixedAmountVoucher, PercentDiscountVoucher)
- list 커맨드를 통해 만들어진 바우처를 조회할 수 있다.
*  적절한 로그를 기록하고 `logback` 설정을해서 에러는 파일로 기록된다.
* 실행가능한 `jar` 파일을 생성한다.
* **입출력**과 **종료 기능**만 구현하였습니다.
* 명령어에 따른 선택적 실행을 구현하였습니다.
* 입출력을 변경할 수 있는 구조로 구현하고자 노력했습니다.
- Console 구현체를 바로 가져와서 사용하는 것이 너무 바람직해 보이지 않아 IOManager를 마치 프록시객체처럼 두어 사용하고자 하였는데, 
바람직하게 구현한 것인지 궁금합니다. 아니면 나중에 입출력 추상화가 필요할 경우까지 Console 구현체를 그냥 바로 사용하는 것이 더 나을까요?
- 클래스와 메소드들의 이름을 올바르게 지은 것인지 궁금합니다.
- 혹시 현재 VoucherController가 너무 많은 책임을 가지게 된 …
> [3기-C] 이수린 SpringBoot Part1 Weekly Mission 제출합니다.

- .gitignore
- src/main/java/org/prgrms/kdt/CommandLineApplication.java
- src/main/java/org/prgrms/kdt/exceptions/InvalidITypeInputException.java
- src/main/java/org/prgrms/kdt/exceptions/WrongSelectException.java
- src/main/java/org/prgrms/kdt/exceptions/WrongVoucherTypeException.java
- src/main/java/org/prgrms/kdt/io/IOManager.java
- src/main/java/org/prgrms/kdt/manager/VoucherAppManager.java
- src/main/java/org/prgrms/kdt/manager/VoucherProviderManager.java
- src/main/java/org/prgrms/kdt/storage/MemoryVoucherStorage.java
- src/main/java/org/prgrms/kdt/storage/VoucherStorage.java
- src/main/java/org/prgrms/kdt/utils/SelectType.java
- src/main/java/org/prgrms/kdt/utils/VoucherType.java
- src/main/java/org/prgrms/kdt/voucher/FixedAmountVoucher.java
- src/main/java/org/prgrms/kdt/voucher/PercentDiscountVoucher.java
- src/main/java/org/prgrms/kdt/voucher/VoucherProvider.java
- src/main/resources/logback.xml
(기본) 바우처 관리 애플리케이션
- Maven / Gradle 로 프로젝트 구성
- 스프링부트 애플리케이션으로 만든다. 프로그램이 시작하면 다음과 같이 지원가능한 명령어를 알려준다.
````
=== Voucher Program ===
Type **exit** to exit the program.
Type **create** to create a new voucher.
Type **list** to list all vouchers.
````
- create / list 커맨드를 지원한다.
- create 커맨드를 통해 바우처를 생성할수 있다. (FixedAmountVoucher, PercentDiscountVoucher)
- list 커맨드를 통해 만들어진 바우처를 조회할 수 있다.
- 적절한 로그를 기록하고 logback 설정을해서 에러는 파일로 기록된다.
- 실행가능한 jar 파일을 생성한다.
- 로그 기능을 추가하였습니다.
- 에러가 발생할 때에만 파일에 저장되도록 사용했습니다. 로그를 확인하는 것은 속한 곳에 따라 기준이  달라지는 것일까요??
- 로그를 기록하고 싶은 곳에서 Logger를 생성하고 사용하는 것으로 이해했습니다. 
Logger를 public으로 선언하여 객체들이 하나의 로거에 접근이 가능하도록 하는 경우가 있을까요? 
현재 어떤 클래스에서 발생한 것인지 기록하기 위해 따로 생성하는 것으로 이해하였습니다!
> [3기-C] 이수린 Spring Weekly Mission (3차) 제출합니다.

- src/main/java/prgms/vouchermanagementapp/controller/CommandExecutor.java
- src/main/java/prgms/vouchermanagementapp/io/IOManager.java
- src/main/java/prgms/vouchermanagementapp/voucher/VoucherManager.java
- src/main/resources/logback.xml
- src/test/java/prgms/vouchermanagementapp/model/AmountTest.java
@hongbin-dev  @seung-hun-h 
[2차 PR](https://github.com/prgrms-be-devcourse/springboot-basic/pull/546#event-7790728414) 까지 구현한 기능에 로깅 기능만 간단히 추가하였습니다. 
2차 PR 피드백은 곧 업로드할 4차 PR에 남기도록 하겠습니다!
- 예외가 발생할 때 로그를 남기는 방식으로 적용하였습니다.
- 예외가 발생시키는 클래스에서 로그를 남길지, 아니면 예외처리를 해주는 곳에서 로그를 남기는 것이 좋을 지 궁금합니다!
> [3기-C] 김선호 SpringBoot Part1 Weekly Mission제출합니다. (3차)

- src/main/java/com/prgrms/springbootbasic/common/exception/GlobalExceptionHandler.java
- src/main/java/com/prgrms/springbootbasic/voucher/controller/VoucherController.java
- src/main/java/com/prgrms/springbootbasic/voucher/controller/VoucherRestController.java
리뷰 반영과 PR이 많이 늦어져서 죄송합니다 ㅠㅠ
이전 미션 "Voucher 기능에 대한 MVC 패턴 적용"에 이어서 진행한 "Voucher 기능에 대한 API 개발하기" 미션입니다.
바우처 서비스의 API 개발하기
전체 조회기능
바우처 추가기능
바우처 삭제기능
바우처 아이디로 조회 기능
[컨트롤러 계층에서의 로깅 리뷰에 대한 질문입니다.](https://github.com/prgrms-be-devcourse/springboot-basic/pull/613#discussion_r1036042331)
[PRG 패턴에 대한 리뷰와 질문입니다.](https://github.com/prgrms-be-devcourse/springboot-basic/pull/613#discussion_r1036043469)
[SSR를 랜더링하는 컨트롤러의 url 네이밍 리뷰에 대한 질문입니다.](https://github.com/prgrms-be-devcourse/springboot-basic/pull/613#discussion_r1045232906)
> [3기-C] 김환 SpringBoot Part3 Weekly Mission 제출합니다.(2차)

- src/main/java/org/devcourse/voucher/app/VoucherService.java
- src/main/java/org/devcourse/voucher/app/dto/VoucherDto.java
- src/main/java/org/devcourse/voucher/console/dto/VoucherDto.java
- src/main/java/org/devcourse/voucher/domain/voucher/DiscountVoucher.java
- src/main/java/org/devcourse/voucher/domain/voucher/FixedAmountVoucher.java
- src/main/java/org/devcourse/voucher/domain/voucher/Money.java
- src/main/java/org/devcourse/voucher/domain/voucher/PercentDiscountVoucher.java
- src/main/java/org/devcourse/voucher/domain/voucher/Voucher.java
- src/main/java/org/devcourse/voucher/domain/voucher/VoucherType.java
- src/main/java/org/devcourse/voucher/repository/VoucherRepository.java
도메인 객체 구현
1. DiscountAmount -> Money 네이밍 변경, Money 필드 값 추가
- ([feat: class 네이밍 변경 및 필드 추가](https://github.com/prgrms-be-devcourse/springboot-basic/commit/7af4b673a9be65d71404f7c61f4ab5cd0f61cc05))
2. Voucher 도메인 모델 구현
- 최상위 Voucher Interface 기능 목록 집합
DiscountVoucher 추상 클래스 ([feat: 도메인 객체 구조 추상화 설계](https://github.com/prgrms-be-devcourse/springboot-basic/commit/2269d6464dd88c47750ddbb78b78e90d6ee68955))
- Fixed, Percent 구체 클래스 ([feat: 도메인 객체 구현](https://github.com/prgrms-be-devcourse/springboot-basic/commit/8af777471c9b3f3d9dbbf00d447cde4e7697e64b))
- 값 변환 및 검증로직 ([feat: checkBalance 반환 값 변경 및 검증 로직 구현](https://github.com/prgrms-be-devcourse/springboot-basic/commit/f1aa75992b250638fd58a659850f8c5dd49845b1))
3. 바우처 타입 구현
- ([feat: 바우처 타입 …
> [4기] 주홍석 도메인 객체 구현 - Voucher

- voucher/src/main/java/org/prgms/voucher/AmountType.java
- voucher/src/main/java/org/prgms/voucher/Application.java
- voucher/src/main/java/org/prgms/voucher/CommandLineApplication.java
- voucher/src/main/java/org/prgms/voucher/Console.java
- voucher/src/main/java/org/prgms/voucher/MemoryVoucherRepository.java
- voucher/src/main/java/org/prgms/voucher/VoucherCreateDto.java
- voucher/src/main/java/org/prgms/voucher/VoucherRepository.java
- voucher/src/main/java/org/prgms/voucher/VoucherService.java
아직 구조를 잡는 중이라 Return Type이나 파라미터는 추후 구현하면서 채워갈 예정입니다..!
1. Voucher 생성 시 필요한 금액 타입 enum 구현 및 createVoucher 메서드에 반영
**commit**
- [feat: 금액 타입을 저장하는 enum 구현](https://github.com/prgrms-be-devcourse/springboot-basic/commit/1d2fe98ea561875c017ac155648a999ad4f2f7dd)
- [refactor: AmountType 변수 명, 지정 값 수정](https://github.com/prgrms-be-devcourse/springboot-basic/commit/eec87cf879ba4a0dab93188c4feff1f67fc2b6d1)
- [feat: AmountType으로 Voucher를 생성하도록 메서드 수정](https://github.com/prgrms-be-devcourse/springboot-basic/commit/65de1b7d89a2c7b93d99c3e05931a50cb21195df)
**설명**    
- 추후 사용자가 해당 문구를 입력하는 경우와 문구와 매칭되는 숫자를 입력하는 경우 처리하기 위하여 `name`, `number`변수를 사용하였습니다.
2. 메모리에 저장하는 VoucherRepository의 구현체인 MemoryVoucherRepository 생성
**commit**
- [feat: 메모리에 저장하는 VoucherRepository 클래스 …
> [4기 - 박현지] Voucher, Command-line Application 구조 설계 및 구현

- README.md
- src/main/java/com/dev/bootbasic/CommandLineApplication.java
- src/main/java/com/dev/bootbasic/util/Constant.java
- src/main/java/com/dev/bootbasic/view/Command.java
- src/main/java/com/dev/bootbasic/view/InputView.java
- src/main/java/com/dev/bootbasic/view/OutputView.java
- src/main/java/com/dev/bootbasic/view/ViewManager.java
- src/main/java/com/dev/bootbasic/view/console/ConsoleInputView.java
- src/main/java/com/dev/bootbasic/view/console/ConsoleOutputView.java
- src/main/java/com/dev/bootbasic/voucher/controller/VoucherController.java
- src/main/java/com/dev/bootbasic/voucher/domain/FixedAmountVoucher.java
- src/main/java/com/dev/bootbasic/voucher/domain/PercentDiscountVoucher.java
- src/main/java/com/dev/bootbasic/voucher/domain/Voucher.java
- src/main/java/com/dev/bootbasic/voucher/domain/VoucherFactory.java
- src/main/java/com/dev/bootbasic/voucher/domain/VoucherType.java
- src/main/java/com/dev/bootbasic/voucher/dto/VoucherDetailsResponse.java
- src/main/java/com/dev/bootbasic/voucher/repository/InMemoryVoucherRepository.java
- src/main/java/com/dev/bootbasic/voucher/repository/VoucherRepository.java
- src/main/java/com/dev/bootbasic/voucher/service/VoucherService.java
- src/test/java/com/dev/bootbasic/voucher/domain/PercentDiscountVoucherTest.java
- src/test/java/com/dev/bootbasic/voucher/domain/VoucherFactoryTest.java
- src/test/java/com/dev/bootbasic/voucher/repository/InMemoryVoucherRepositoryTest.java
- src/test/java/com/dev/bootbasic/voucher/service/VoucherServiceTest.java
PR을 날리고보니 수정할 부분이 몇가지보여.. 수정했습니다. 죄송합니다ㅠ
예외테스트를 진행할때 예외메시지의 내용은 검증하지 않음
바우처 ID를 검증하는 방법으로 변경
바우처 팩토리를 멤버변수로 변경
바우처 ID를 바우처 팩토리에서 생성함
null 검증 중복 메서드 제거
바우처를 조회할때 ID도 함께 조회함
팩토리 메서드 네이밍 변경
바우처 타입 반환 로직변경
- 현재는 커스텀 예외가 아닌 표준 예외를 사용하고 있습니다. 예외메시지를 검증하지 않으면 표준 예외이기 때문에 정확한 검증이라고 할 수 있을까? 라는 의문이 들었습니다. 예외메시지를 검증하지 않고 커스텀 예외를 만들어 검증하는 것도 고려해봐도 될까요?
- 리뷰반영의 대해서는 Squash Merge를 사용해봤는데.. 오히려 보기 불편하신지 궁금합니다.
- DTO 역할을 하는 VoucherDetailsResponse,VoucherCreateRequest 클래스가 서비스, 컨트롤러,콘솔애플리케이션 모두에 사용되고 있습니다. DTO를 분리하는 것이 좋다고 생각되지만 그렇게 되면 현재 프로젝트 크기에 비해 너무 많은 DTO가 생성된다고  생각합니다. 어떻게 생각하시는지 궁금합니다.
> [4기] 고범준 3차 사용자의 콘솔 입력, 출력 구현

- src/main/java/org/devcourse/voucher/domain/voucher/VoucherType.java
- src/main/java/org/devcourse/voucher/domain/voucher/policy/FixedDiscountPolicy.java
- src/test/java/org/devcourse/voucher/domain/voucher/VoucherTest.java
- src/test/java/org/devcourse/voucher/domain/voucher/VoucherTypeTest.java
- src/test/java/org/devcourse/voucher/domain/voucher/policy/FixedDiscountPolicyTest.java
- src/test/java/org/devcourse/voucher/domain/voucher/policy/PercentDiscountPolicyTest.java
> [4기] 주홍석 Voucher 도메인 테스트 코드 작성

- src/main/java/org/devcourse/voucher/app/VoucherManagerService.java
- src/main/java/org/devcourse/voucher/domain/voucher/Voucher.java
- src/main/java/org/devcourse/voucher/domain/voucher/policy/DiscountPolicy.java
- src/main/java/org/devcourse/voucher/repository/InMemoryVoucherRepository.java
- src/main/java/org/devcourse/voucher/repository/VoucherRepository.java
- src/test/java/org/devcourse/voucher/app/VoucherManagerServiceTest.java
- src/test/java/org/devcourse/voucher/repository/InMemoryVoucherRepositoryTest.java
바우처 생성, 조회 로직 관련 서비스, 레포지토리 구현
1. 바우처 생성, 전체 조회 ([feat: 바우처 서비스 로직 구현](https://github.com/prgrms-be-devcourse/springboot-basic/commit/10ec3bc063c64ac4186728ef400dd143d7118620))
2. InMemory Repo 생성 ([feat: 바우처 repo 생성](https://github.com/prgrms-be-devcourse/springboot-basic/commit/c6995170a1b160694771c1c92080b720129ca150))
- Map 사용해서 저장
- AtomicLong 사용해서 id sequence 값 생성
3. ([feat: 필요 게터 생성](https://github.com/prgrms-be-devcourse/springboot-basic/commit/5fdcade87b91e85939734f34a70a02497ed0d279))
4. 게터 없이 내부에서 새로운 객체 생성 후 반환 ([feat: getter 제거 및 로직 수정](https://github.com/prgrms-be-devcourse/springboot-basic/pull/718/commits/4fe08f7cc2c95aa749172e2fc2c1f9e898664718))
~~([feat: storage deleteAll 메소드 추가](https://github.com/prgrms-be-devcourse/springboot-basic/commit/1c730aa39ee432b7b0ab4ea3fad5f …
> [4기] 주홍석 바우처 생성/조회 로직 구현

- .gitignore
- src/main/java/com/dev/bootbasic/CommandLineApplication.java
- src/main/java/com/dev/bootbasic/user/controller/UserController.java
- src/main/java/com/dev/bootbasic/user/controller/dto/UserCreateRequest.java
- src/main/java/com/dev/bootbasic/user/controller/dto/UserCreateResponse.java
- src/main/java/com/dev/bootbasic/user/domain/User.java
- src/main/java/com/dev/bootbasic/user/repository/UserRepository.java
- src/main/java/com/dev/bootbasic/user/service/UserService.java
- src/main/java/com/dev/bootbasic/util/Constant.java
- src/main/java/com/dev/bootbasic/view/InputView.java
- src/main/java/com/dev/bootbasic/view/ViewManager.java
- src/main/java/com/dev/bootbasic/view/console/ConsoleInputView.java
- src/main/java/com/dev/bootbasic/view/dto/VoucherDetailsViewResponse.java
- src/main/java/com/dev/bootbasic/voucher/domain/VoucherType.java
- src/main/java/com/dev/bootbasic/voucher/dto/VoucherDetailsResponse.java
- src/main/java/com/dev/bootbasic/voucher/service/VoucherService.java
- src/main/resources/logback.xml
[3차 리뷰](https://github.com/prgrms-be-devcourse/springboot-basic/pull/694#discussion_r1243533737) 에서 도진님께서 주신 피드백을 반영했으나 승훈님이 다시 코멘트를 주셔 고민을 해봤는데.. 다시 롤백하는 방향으로 결정을 했습니다. 이전 방식으로 돌아간 이유는  이 정보는 콘솔에서 밖에 사용이 안될거같은데 그러면 View에서 만들어주는게 더 적절하다고 판단 했습니다!
코드에 코멘트 남기도록 하겠습니다!
> [4기] 고범준  로깅, 유저, 유저 레포지토리 구현

- .gitignore
- build.gradle
- src/main/java/com/dev/voucherproject/VoucherProjectApplication.java
- src/main/java/com/dev/voucherproject/controller/console/VoucherMenuController.java
- src/main/java/com/dev/voucherproject/controller/web/HomeController.java
- src/main/java/com/dev/voucherproject/controller/web/VoucherAdminController.java
- src/main/java/com/dev/voucherproject/controller/web/config/WebConfig.java
- src/main/java/com/dev/voucherproject/controller/web/exception/RestControllerAdvice.java
- src/main/java/com/dev/voucherproject/controller/web/request/VoucherCreateRequest.java
- src/main/java/com/dev/voucherproject/controller/web/response/Response.java
- src/main/java/com/dev/voucherproject/model/service/VoucherService.java
- src/main/java/com/dev/voucherproject/model/storage/io/VoucherFileWriter.java
- src/main/java/com/dev/voucherproject/model/storage/voucher/CsvFileVoucherStorage.java
- src/main/java/com/dev/voucherproject/model/storage/voucher/VoucherDao.java
- src/main/java/com/dev/voucherproject/model/voucher/FixedAmountVoucher.java
- src/main/java/com/dev/voucherproject/model/voucher/PercentDiscountVoucher.java
- src/main/java/com/dev/voucherproject/model/voucher/Voucher.java
- src/main/java/com/dev/voucherproject/model/voucher/VoucherApplication.java
- src/main/java/com/dev/voucherproject/model/voucher/VoucherDto.java
- src/main/java/com/dev/voucherproject/model/voucher/VoucherPolicy.java
- src/main/java/com/dev/voucherproject/view/Console.java
- src/main/resources/templates/home.html
- src/main/resources/templates/vouchers/createForm.html
- src/main/resources/templates/vouchers/home.html
- src/main/resources/templates/vouchers/voucher.html
- src/main/resources/templates/vouchers/vouchers.html
- src/test/java/com/dev/voucherproject/voucher/CsvFileVoucherStorageTest.java
- src/test/java/com/dev/voucherproject/voucher/VoucherDaoTest.java
기존에 올렸던 PR이 **Spring MVC를 적용하여 JSON과 XML을 지원하는 REST API 개발하기** 까지 포함하여 올리는 바람에
닫고 다시 올렸습니다.
> [4기 - 박형진] SpringBoot Part3 Weekly Mission 첫 번째 PR 제출합니다.

- kdt-spring-voucher/.gitignore
- kdt-spring-voucher/pom.xml
- kdt-spring-voucher/src/main/java/org/prgrms/kdt/AppConfiguration.java
- kdt-spring-voucher/src/main/java/org/prgrms/kdt/customer/Customer.java
- kdt-spring-voucher/src/main/java/org/prgrms/kdt/customer/repository/CustomerJdbcRepository.java
- kdt-spring-voucher/src/main/java/org/prgrms/kdt/customer/repository/CustomerRepository.java
- kdt-spring-voucher/src/main/java/org/prgrms/kdt/storage/FileVoucherStorage.java
- kdt-spring-voucher/src/main/java/org/prgrms/kdt/storage/JdbcVoucherStorage.java
- kdt-spring-voucher/src/main/java/org/prgrms/kdt/storage/MemoryVoucherStorage.java
- kdt-spring-voucher/src/main/java/org/prgrms/kdt/storage/VoucherStorage.java
- kdt-spring-voucher/src/main/resources/application.properties
- kdt-spring-voucher/src/test/java/org/prgrms/kdt/customer/repository/CustomerJdbcRepositoryTest.java
- kdt-spring-voucher/src/test/java/org/prgrms/kdt/storage/JdbcVoucherStorageTest.java
- kdt-spring-voucher/src/test/java/org/prgrms/kdt/storage/VoucherStorageTest.java
- kdt-spring-voucher/src/test/java/org/prgrms/kdt/voucher/FixedAmountVoucherTest.java
- kdt-spring-voucher/src/test/java/org/prgrms/kdt/voucher/PercentDiscountVoucherTest.java
**(기본)** **바우처 관리 애플리케이션**
- 가능한 많은 단위 테스트코드를 작성하려고 노력해보세요.
- 엣지 케이스(예외 케이스)를 고려해서 작성해주세요.
- Hamcrest 의 메쳐들을 다양하게 작성해보고 익숙해져 보세요.
- customers 테이블 정의 및 추가
- CustomerRepository 추가 및 JdbcTemplate을 사용해서 구현
- 바우처에 엔터티에 해당하는 vouchers 테이블을 한번 정의해보세요.
- 바우처 레포지토리를 만들어보세요. (JdbcTemplate을 사용해서 구현)
- 기존의 파일에서 바우처를 관리한 것을 vouchers 테이블을 통해서 CRUD가 되게 해보세요.
위 부분 구현하였습니다!
> [4기 - 김재웅] SpringBoot Part2 Weekly Mission PR 제출합니다.

- build.gradle
- src/main/java/com/prgms/springbootbasic/AppConfig.java
- src/main/java/com/prgms/springbootbasic/SpringWebInitializer.java
- src/main/java/com/prgms/springbootbasic/command/VoucherCommand.java
- src/main/java/com/prgms/springbootbasic/controller/VoucherController.java
- src/main/java/com/prgms/springbootbasic/domain/FixedAmountVoucher.java
- src/main/java/com/prgms/springbootbasic/domain/PercentAmountVoucher.java
- src/main/java/com/prgms/springbootbasic/domain/Voucher.java
- src/main/java/com/prgms/springbootbasic/dto/ModifiedVoucherDto.java
- src/main/java/com/prgms/springbootbasic/dto/NewVoucherDto.java
- src/main/java/com/prgms/springbootbasic/dto/VoucherDto.java
- src/main/java/com/prgms/springbootbasic/exceptionhandler/VoucherExceptionHandler.java
- src/main/java/com/prgms/springbootbasic/persistent/VouchersInDB.java
- src/main/java/com/prgms/springbootbasic/service/VoucherService.java
- src/main/java/com/prgms/springbootbasic/ui/VoucherOutputView.java
- src/main/java/com/prgms/springbootbasic/util/FormatCSV.java
- src/main/webapp/WEB-INF/classes/application.yaml
- src/main/webapp/WEB-INF/views/403.html
- src/main/webapp/WEB-INF/views/new-vouchers.html
- src/main/webapp/WEB-INF/views/update-vouchers.html
- src/main/webapp/WEB-INF/views/vouchers.html
- src/test/java/com/prgms/springbootbasic/util/FormatCSVTest.java
📌 과제 설명
👩‍💻 요구 사항과 구현 내용
- thymeleaf로 뷰를 만들었습니다. 
- controller 어노테이션이 붙은 VoucherController를 만들었습니다. url로 요청이 들어오면 뷰 페이지를 반환하도록 했습니다. 
- service 어노테이션이 붙은 VoucherService를 만들었습니다. 해당 클래스는 VouchersStorage를 의존하고 있습니다. 
VoucherService는 dto를 엔티티로 바꾸고 다시 dto로 바꾸어 반환하고 있습니다.
- record로 dto를 만들었습니다. dto 내에 dto <-> entity, entity <-> dto 변환 로직이 있습니다.
✅ PR 포인트 & 궁금한 점
1️⃣ 지금은 dto를 엔티티로 엔티티를 dto로 변환하는 로직을 dto가 가지고 있습니다. 만약 변환하는 로직이 복잡해지는 경우에만 mapper라는 클래스를 따로 만드는게 맞는건가요??
> [4기 - 한희나] SpringBoot Part3 Weekly Mission 첫 번째 PR 제출합니다.
